### ISSUE TITLE
add S3 support for build artefacts and packages

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#101]
* [x] add S3 buckets
 * [x] add deployment from travis builds (mac)
 * [x] add deployment from appveyor builds (win)
 * [ ] add deployment for linux

**Comment by chadfurman** [comment]
Following up on this.  I know this was to result in compiler-optimized EBS mac/windows binaries.  What's an ETA?

**Comment by agouaillard-cosmo** [comment]
it should be working, but i have not checked myself.

**Comment by agouaillard-cosmo** [comment]
Requested access to the S3 bucket to validate packages.

**Comment by agouaillard-cosmo** [comment]
S3 buckets and travis builds deployment validated.
![Screen Shot 2019-08-07 at 12 14 12 PM](https://user-images.githubusercontent.com/27793645/62594474-60b99800-b90d-11e9-99ac-42401e76e170.png)

**Comment by agouaillard-cosmo** [comment]
deployment for windows added
