### ISSUE TITLE
EBS: Important UI Features Remaining

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#108]
- [x] Remove all streaming services. Only Evercast. (duplicate of #95 )
   - https://www.screencast.com/t/VQqaGEiW
- [x] When you enter server name, server room or stream key into EBS, empty space at the end should not cause EBS to crash.  A simple "trim" of the input is sufficient
- [x] Remove the recording button from the UI (duplicate of #94)
   - https://www.screencast.com/t/3JVvMxiuO
- [x] Remove recording options from “output” tab in settings
   - https://www.screencast.com/t/NB4g0tAK

**Comment by agouaillard-cosmo** [comment]
Basics: one ticket, one task.

**Comment by agouaillard-cosmo** [comment]
all dispatched in separate tickets.
