### ISSUE TITLE
EBS: VP9 support

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#111]
during tests of the 7/11 2:00am delivery, it appears that it still connects as VP8.
Tests on Evercast side by hardcoding VP9 instead of using the output of get_codec() in the streaming code are reported to have been successful. 

TODO CoSMo: double check, with video recording of the experiment, that EBS build on windows can connect successfully to dev infra with VP9.

@chadfurman

**Comment by chadfurman** [comment]
Fyi this is where we set "videocodec": "vp9" https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/m73-port/plugins/websocket-client/EvercastWebsocketClientImpl.cpp#L247

**Comment by agouaillard-cosmo** [comment]
works.
