### ISSUE TITLE
EBS - Set default temporal and spatial resolution.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#116]
Set default FPS in settings to 60
https://www.screencast.com/t/9N2zeWqG

  Set default audio bitrate to 320 and 4000 for video bitrate
https://www.screencast.com/t/UylEzMrQ1

Dispatch of #107

**Comment by agouaillard-cosmo** [comment]
Those numbers seems unreasonable, and will very likely provide a poor UX. Now, I will set them as default as requested anyway, but I strongly suggest you reconsider.

**Comment by agouaillard-cosmo** [comment]
Update: fps can stay at 30

**Comment by agouaillard-cosmo** [comment]
Update: video input should be 1080p, video composition 1080p, 30fps, bilinear
![M73v23 2-2-Video-Composition-settings](https://user-images.githubusercontent.com/27793645/67058261-ebd2bd80-f108-11e9-983f-e9af7b12c725.png)

**Comment by ludocosmo** [comment]
How to test...
1) Remove user setting.
On Mac: rm -rf $HOME/Library/Application\ Support/Evercast
On Windows: delete directory C:\Users\<username>\AppData\Roaming\Evercast

2) Install EBS

3) Launch EBS and open Settings/Video
You should see this window with these values.
![ticket116_after_default_settings_for_video](https://user-images.githubusercontent.com/30816985/67174666-76f7d000-f3f5-11e9-9082-3dbdf7d66124.png)

**Comment by agouaillard-cosmo** [comment]
implemented.
@namvuCosmo is there a kite test for it?
