### ISSUE TITLE
EBS - Remove “Use Buffering” option under video capture device settings.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#117]
https://www.screencast.com/t/4QjxAY8Vx5Ja
dispatched from #107

**Comment by agouaillard-cosmo** [comment]
@chadfurman, is it a rebase item (it was in ebs, and needs to be ported) or a new item?

**Comment by agouaillard-cosmo** [comment]
on main GUI, click on add source, click on "video capture source", click on OK, then you have the UI of interest, whose screenshot is above.

**Comment by ludocosmo** [comment]
WARNING: UI for video capture device settings is different for Mac and Windows.
Windows version has more options.
![ticket117_windows_video_capture_device](https://user-images.githubusercontent.com/30816985/67186860-8427b580-f41b-11e9-9040-ecc1dca47689.png)
