### ISSUE TITLE
EBS - Set “transform” default to fit to screen when a video capture device or display capture source is selected.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#118]
https://drive.google.com/file/d/16pNMN5ozXokRgiOPK1gFhFs98PDnJ11r/view?usp=sharing.
Dispatched from #107

**Comment by agouaillard-cosmo** [comment]
@chadfurman, is it a rebase item (it was in ebs, and needs to be ported) or a new item?

**Comment by agouaillard-cosmo** [comment]
once the corresponding source has been added to the scene, right-click on it to check the default setting.

**Comment by ludocosmo** [comment]
The "transform" menu is a contextual menu opened on a mouse click. The items displayed under the "transform" menu are independent of the capture source selected, so it seems difficult to try to modify the status of an item depending on which capture source is selected.
In addition, the items of a contextual menu do not have default values. The closer to a "default value" could be to add a check sign in front of the "fit to screen" item.

**Comment by ludocosmo** [comment]
I can move the "fit to screen" item to the top of the list of the "transform" menu, as shown below.

Current "transform" menu:
![ticket118_before](https://user-images.githubusercontent.com/30816985/74141782-8a43db00-4c32-11ea-8ce1-5a545c73b794.png)

Modified "transform" menu with "fit to screen" on top of the list:
![ticket118_after](https://user-images.githubusercontent.com/30816985/74141852-a47db900-4c32-11ea-92d3-47d3b6e30c53.png)

**Comment by agouaillard-cosmo** [comment]
LGTM
