### ISSUE TITLE
EBS - Set downscale filter to “Bilinear” by default.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#121]
https://gyazo.com/ec595a3de063df4358e668a8931691fe
Dispatched from #107.

**Comment by agouaillard-cosmo** [comment]
@chadfurma, is it a rebase item (it was in ebs, and needs to be ported) or a new item?

**Comment by agouaillard-cosmo** [comment]
to do as #116

**Comment by ludocosmo** [comment]
Fixed in #116
