### ISSUE TITLE
the EBS executable icon is not modified to abs icon as it should and is using the original OBS icon.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#130]
reported by brad
https://i.gyazo.com/71ebc3d38f0196d16125c94cee0b47b7.png

@chadfurman

**Comment by agouaillard-cosmo** [comment]
most of the icons and other graphic elements are under /UI/Forms/Image, but of course, for isntallers and packagers the graphic files are all around. For window, the icon is already under the cmake/ directory (where only script should be), under winrc. Wrong in many respects, but we re not being asked to clean obs, just to change the graphic file.

**Comment by agouaillard-cosmo** [comment]
just in case, note that windows is creating a DB in each folder with icons rendering, and if you update the icon later, it will still render the original one. See attached screenshot that show that the real icons (in properties menu) is EBS, but the one that shows in the explorer is still the old OBS icon.
![icon_db-not-always-updated](https://user-images.githubusercontent.com/27793645/62187388-cb158a00-b39b-11e9-9fb9-3478778ffdf9.png)

**Comment by chadfurman** [comment]
If it is a windows DB issue, why is it happening this way in the EBS folder?  How is the DB being corrupted in this way on multiple computers?

**Comment by agouaillard-cosmo** [comment]
Please read the following material and revert:
- https://www.windowscentral.com/how-reset-icon-cache-database-windows-10

**Comment by agouaillard-cosmo** [comment]
if you install on a machine that had a previous install in the past, even after deleting everything, the icon cache still has the original icon in the cache. The above screenshot show you exactly that case where the executable icon is the correct one, as shown in the property panel, but the one in the icon cache shown in Explorer is still the old one.

You have two ways to address this:
- change the icon name
- flush the icon cache.

Since we are not going to change the icon name for each build, the real solution is to validate on a new machine, or to use the same machine but to flush the icon cache.

Note that simply erasing the files on disk, or uninstalling, followed by a "fresh" install is not enough since you would not flush the windows icon cache. 

Note that this is not a failure of the installer, or the packaging, it s at best a failure of the validation process, and otherwise, a feature of windows, very well documented (type "icon cache" in google).
