### ISSUE TITLE
EBS - Claim about audio regression in EBS-m73-21

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#131]
reported by brad

![Screen Shot 2019-07-26 at 10 20 58 AM](https://user-images.githubusercontent.com/27793645/61958417-48ea2780-af8f-11e9-84ea-570b56d07585.png)

As described, the problem is not reproducible. Screen recording does not allow to reproduce problems, which can be due to any kind of problem, which I'm not even going to start listing. 

I do not close this ticket, but until a detailed step-by-step scenario that leads to the problem become available, not time will be spend poking in the dark to try to find a problem that is likely not here in the first place, given the track record of sloppy testing and false claims from this tester.

@chadfurman

**Comment by chadfurman** [comment]
The audio regression is an audio selection issue in OBS 21, fixed in OBS 23.

**Comment by agouaillard-cosmo** [comment]
I'm re-opening this ticket, so we remember to double check upon upgrading to v23
