### ISSUE TITLE
Clearing settings on windows causes "Twitch" selection to show again

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#135]
Following the instructions here:
https://youtu.be/QMnbKlnkh18?t=48

(File -> Show Settings Folder -> go up a directory -> delete obs-studio folder)

Then Twitch shows up again when going to EBS -> stream selection:

https://gyazo.com/68a1656e8613ba35573cc410e53d5533

**Comment by agouaillard-cosmo** [comment]
is it a windows only bug?

**Comment by chadfurman** [comment]
It is only confirmed in windows, so let's say for the sake of this ticket that the scope of this bug is Windows only

**Comment by agouaillard-cosmo** [comment]
cannot reproduce.
![delete-obs-settings](https://user-images.githubusercontent.com/27793645/62190745-af62b180-b3a4-11e9-9795-a635a643fb47.png)

![twitch-cannot-reproduce](https://user-images.githubusercontent.com/27793645/62190756-b4276580-b3a4-11e9-82f9-63990345ef0e.png)
