### ISSUE TITLE
New Windows installer produces folder w/o exe

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#136]
See screenshot:

![Screenshot (1)](https://user-images.githubusercontent.com/635170/62222632-b0ceb280-b381-11e9-8d8d-32fb1c48dee2.png)

**Comment by agouaillard-cosmo** [comment]
can you please refer to the full name of the installer?

**Comment by agouaillard-cosmo** [comment]
I'm preparing a new installer anyway, let's close this one for now. In future reports, please include the full name of the installer.
