### ISSUE TITLE
EBS: Settings do not appear to be saved properly on Windows

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#138]
**Installer name**: ebs-studio-x64-m73-21-190801-2.exe

**Video demonstrating problem**: https://www.youtube.com/watch?v=mc9DIYI1opo&feature=youtu.be

it's actually taking the bit rate you set. it's just not showing the number
for example, if I set it at 8000 it goes back to showing 2000 but it streams at 8

**Comment by agouaillard-cosmo** [comment]
yes, know bug. Reproduced.

**Comment by agouaillard-cosmo** [comment]
fixed.
