### ISSUE TITLE
EBS: found additional locations where branding remains "OBS"

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#151]
* C:\Users\chad\projects\EBS\OBS-studio-webrtc
* C:\Users\chad\AppData\Roaming\obs-studio
* C:\Program Files\EBS Studio (64bit)\obs-plugins
* C:\Program Files\EBS Studio (64bit)\data\libobs
* C:\Program Files\EBS Studio (64bit)\data\obs-plugins
* C:\Program Files\EBS Studio (64bit)\data\obs-studio
* multiple files in the include folder ... 

Curious about why, LOE to fix, etc

I'm guessing at this point it's because we're doing a skin layer as opposed to a search-and-replace on the string, right?
![Screenshot (2)_LI](https://user-images.githubusercontent.com/635170/62858976-e2247800-bcc9-11e9-9bfb-2b2c313c4c32.jpg)

**Comment by agouaillard-cosmo** [comment]
What does LOE stand for?

**Comment by chadfurman** [comment]
LOE stands for level of effort

**Comment by chadfurman** [comment]
What I deemed sufficient was that "obs" strings before build/packaging were acceptable as the end-user would never see those strings.  "OBS" strings once the application is installed on an end-user's computer are definitely visible to the end user because:
1) to properly flush settings, you must delete the settings folder.  This folder is the "obs-studio" folder in the AppData directory
2) Given that the start menu doesn't work, the user is encouraged to open up the Program Files folder directly and from there it's not a stretch that the user would see the obs labels on the includes

As for the maintenance burden, perhaps there's a strategic way to approach this.  Something like a find-replace at build time or similar.  This does not address the fact that this is a daunting task, however.

* C:\Users\chad\projects\EBS\OBS-studio-webrtc -- you are correct, this is my local clone.  Thank you
* As for the rest, these are end-user visible.  

Let's leave this ticket open for now, as this hasn't come up yet in discussions with the client but it would not surprise me if they do eventually notice and raise it as a concern...

**Comment by agouaillard-cosmo** [comment]
"Let's leave this ticket open for now, as this hasn't come up yet in discussions with the client but it would not surprise me if they do eventually notice and raise it as a concern..."

Usually it's better to close the tickets untill a real problem arise, so we can focus on tickets which represent problem that really need to be addressed. 

I will go ahead and close this ticket. Please re-open it if it becomes a real problem with any customer.
