### ISSUE TITLE
SPANK.live Deprecated?

### ISSUE THREAD

**Issue by SpankChase** [CoSMoSoftware/OBS-studio-webrtc#152]
On the [wiki](https://github.com/CoSMoSoftware/OBS-studio-webrtc/wiki) page, there is a note that SPANK.live support was deprecated with m73.

Is that still the case?
If so, what needs to be done to fix?

Also, will the free libwebrtc community package be available for download soon? Right now one is directed to schedule a 15-minute consultation on Calendly.

**Comment by chadfurman** [comment]
I may be wrong, but the CI scripts I think work with a community package. That is, if you use the CI scripts locally to build, my understanding is the resulting package uses the community libwebrtc

I could be wrong, and I hope I'm not adding confusion

**Comment by agouaillard-cosmo** [comment]
Hi chase, welcome back.

For every big revision (update of libwebrtc, update of OBS), we check if there is activity with the service or server the are supported in the code:
- support from the server/service
- community support
- cosmo internal support
- cosmo paid support
There was nothing of these in place when 73 was branched out.

Your current builds are based on m69, you could use the corresponding branch of this repository, and:
- requests a community package from CoSMo on the website. Note that the community package have a cosmo logo watermark on the top left hand corner. 
- Alternatively, you can recompile libwebrtc yourself, it works out of the box. 
- Finally, if you do not have the ressource and expertise available, you could contact us for help.

**Comment by agouaillard-cosmo** [comment]
@SpankChase does it answer your question? Can I close the ticket?

**Comment by SpankChase** [comment]
@agouaillard-cosmo Yessir! Thanks, Dr. Alex. I'll close and reach out if I need additional help. :sweat_smile:
