### ISSUE TITLE
EBS - cannot install libwebrtc on Mojave 10.14.4

### ISSUE THREAD

**Issue by skastr0** [CoSMoSoftware/OBS-studio-webrtc#154]
I apologize if this is the wrong spot to open this ticket. Let me know if there's a better place to move this to.

### setup:
libwerbtc installer: libWebRTC-73.0-x64-Rel-H264.dmg
computer: MacBook Pro (15-inch, 2018)
macOS: Mojave 10.14.4

### step-by-step:
1. open libWebRTC-73.0-x64-Rel-H264.dmg
2. extract libWebRTC-73.0-x64-Release-H264-Bitcode.pkg out (or move to step 3)
3. open libWebRTC-73.0-x64-Release-H264-Bitcode.pkg
4. proceed through the options until Installation
5. click Install Anyway on the incompatibility warning
6. installation fails.

**Comment by agouaillard-cosmo** [comment]
For the mean time this is the right place.
This is a known issue, We use Apple's PackageMaker which has been fully deprecated now. Internal cosmo ticket (72). We contacted Kitware and validated that "DragNDrop" is the new pack generator to be used on Mac.

The ticket is in the pile to be addressed later this month. As a workaround for the time being for OBS/EBS we provide zipped versions of the install directory created by the unit tests.

**Comment by agouaillard-cosmo** [comment]
Note that the reference hardware for testing and validation is as follows:
"a MacBook Pro 11,4 (MJLQ2LL/A) with 10.12."
With the current reference document, this is not a bug.

Nowhere the distinction between a "build computer" and a "end-user computer" has been made. if a different configuration for Evercast builds bots or dev. computers is needed, and if 10.14 needs to be supported for those, please add it to the reference document so expectations are clear, and met.

**Comment by agouaillard-cosmo** [comment]
new installer has been delivered.
