### ISSUE TITLE
EBS - Meta Ticket for UI changes introduced by v23.2 update

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#157]
1. Every mention to recording and / or replay should be removed from the UI.
2. Settings that do not tie to WebRTC Settings should be addressed.

![Screen Shot 2019-08-23 at 11 24 01 AM](https://user-images.githubusercontent.com/27793645/63565103-36690b00-c59a-11e9-9d40-4a6122da6a7f.png)
![Screen Shot 2019-08-23 at 11 24 42 AM](https://user-images.githubusercontent.com/27793645/63565108-3cf78280-c59a-11e9-809b-8bef1a6ad7d0.png)

The above two screenshots are in the OUTPUT setting panel.

![Screen Shot 2019-08-23 at 11 25 19 AM](https://user-images.githubusercontent.com/27793645/63565116-408b0980-c59a-11e9-96ad-1bdb54c352ea.png)

Since today all the audio pipeline in WebRTC is automatic, this setting panel can lead to unmet expectations. What should we do? Grey it until we wire it? Remove it all together for now?

![Screen Shot 2019-08-23 at 11 25 57 AM](https://user-images.githubusercontent.com/27793645/63565120-4254cd00-c59a-11e9-8d66-d090f93e8861.png)

The shortcuts needs to be fixed to remove mention of recording or replay.

![Screen Shot 2019-08-23 at 11 26 21 AM](https://user-images.githubusercontent.com/27793645/63565123-441e9080-c59a-11e9-9987-6edc7075e65e.png)

Mentions of recording and replay should be removed. It is not sure how many of those settings are actually used in the WebRTC Pipeline. If they are applied before the output plugin kicks in, they should have an effect, but the effect is today unknown. If they don't we should not let the user interact with them to manage expectations.

**Comment by chadfurman** [comment]
The ticket is very clear, thank you again.  My understanding is that there are lots of settings that may or may not affect webrtc pipeline in both 65.22 and 73.21 so I'd assume those new ones aren't deal breakers.  The recording UI is.a.good catch -- we would.wanr to remove that

**Comment by agouaillard-cosmo** [comment]
all of the items have been addressed.
What to do with the audio panel is left for a later discussion.
Same about the "delay" option in the advanced settings.
