### ISSUE TITLE
TLS1.0 in janus

### ISSUE THREAD

**Issue by kindritskyiMax** [CoSMoSoftware/OBS-studio-webrtc#159]
Hi. I just noticed that janus websocket stuff uses old tls1.0 when millicast and others using tls1.2. I run in such a problem when OBS-webrtc 2.8 release on Windows 10 failing to connect because if old tls verion. 
Old tls usage https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/master/plugins/websocket-client/JanusWebsocketClientImpl.cpp#L155

**Comment by agouaillard-cosmo** [comment]
Thank you for your bug report. 
I will check with lorenzo, and modify the code if need be.
I will get back to you next week on this.

**Comment by kindritskyiMax** [comment]
Worth mentioning that my janus server is running and accepting connections on ws port (not wss) and placed after some kind of nginx which I can not manage, hence can not enable old TLS1.0.

**Comment by agouaillard-cosmo** [comment]
It should be fixed now in branch m73v21
