### ISSUE TITLE
where is "webrtcVersion.h"?

### ISSUE THREAD

**Issue by laowangnj** [CoSMoSoftware/OBS-studio-webrtc#16]
[ 56%] Building CXX object UI/CMakeFiles/obs.dir/window-basic-status-bar.cpp.obj

window-basic-status-bar.cpp
C:\cosmo\OBS-studio-webrtc\UI\window-basic-status-bar.cpp(9): fatal error C1083:
 Cannot open include file: 'webrtcVersion.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe' : return
 code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

**Comment by agouaillard-cosmo** [comment]
What version of libwebrtc do you use, and where did you get it?

**Comment by laowangnj** [comment]
libwebrtc-62.252-x64-Release-rtti-msvc2015.exe from “https://s3-ap-southeast-1.amazonaws.com/webrtc-installer/version62/libwebrtc-62.252-x64-Release-rtti-msvc2015.exe”

**Comment by myhuInShangHai** [comment]
how can i setting obs studio stream url and roomid for my local janus server？
and then where can i see the obs stream？

**Comment by agouaillard-cosmo** [comment]
We are addressing the issue, and you should have a new version of the code that does not require this file before the end of the week.

**Comment by laowangnj** [comment]
Thanks

**Comment by agouaillard-cosmo** [comment]
pending #19

**Comment by cosmo-rn** [comment]
Modifications have been made so that "webrtcVersion.h" is found during compilation.

**Comment by agouaillard-cosmo** [comment]
@laowangnj can you confirm the new version works for you?

**Comment by laowangnj** [comment]
Build successfully. 
But "Packaging",
How to "cd build
cpack"

**Comment by cosmo-rn** [comment]
just type "cpack" in the build folder.

**Comment by laowangnj** [comment]
after installed nsis,  
cpack out package, 
But the package lost some dlls, such Qt, DX, opengl

**Comment by cosmo-rn** [comment]
The issue has been fixed.
Please pull the latest commit.
