### ISSUE TITLE
EBS - Streaming VP9 to PCs running Chrome has freezes

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#161]
**Installer**: ebs-studio-x64-m73-travis-mac-111-gd735b8ce-modified.exe
**EBS Publisher Specs**: https://gyazo.com/762e70a8f2e744bdcc534ee0e5527526
**Subscriber Specs**: https://gyazo.com/36cf2487ac3691235dc66bd52297dbc7
**Browser Version**: Chrome 77
The issue seems to only happen when receiving in Windows.  On Macs of various specifications, the reports are that the VP9 stream is decoded without issue.  An example of a mac that works without problems for this issue is a 4980HQ 4 cored i7

Issue happens at both 720 and 1080 as well as 30fps and 60fps.  Base and Canvas resolutions the same.  Device and/or display capture, same problem.  320 or 160 audio bitrate same thing.

**Comment by agouaillard-cosmo** [comment]
Good ticket, easy to reproduce => faster to fix.

**Comment by agouaillard-cosmo** [comment]
Started.
