### ISSUE TITLE
can't see obs stream 

### ISSUE THREAD

**Issue by myhuInShangHai** [CoSMoSoftware/OBS-studio-webrtc#17]
Launch OBS, go to settings, select the stream tab and change the URL to your JANUS : wss://janus1.cosmosoftware.io
Put 1234 for the room.

After you can start streaming, OBS will connect to the default room and if you have any suscriber present in the room, you will see the OBS stream. https://clientweb.cosmosoftware.io/janusweb/videoroomtest.html

follow the steps i haven't seen the obs stream.https://clientweb.cosmosoftware.io/janusweb/videoroomtest.html

how can i setting obs stream url and room?

**Comment by cosmo-rn** [comment]
Go to the settings, select the stream tab then change the value of the URL and the room to the following:
URL: wss://janus1.cosmosoftware.io
room: 1234

![capture](https://user-images.githubusercontent.com/35674843/39849031-f60379d0-543c-11e8-9e66-a38f4503e5ae.PNG)

**Comment by myhuInShangHai** [comment]
thanks 
i have a question:

Configure JANUS
https://github.com/meetecho/janus-gateway. Configure a JANUS server using the video room plugin with websocket protocol activate. You can use their html demo.

OBS settings
Launch OBS, go to settings, select the stream tab and change the URL to your JANUS : wss://janus1.cosmosoftware.io
Put 1234 for the room.

After you can start streaming, OBS will connect to the default room and if you have any suscriber present in the room, you will see the OBS stream. https://clientweb.cosmosoftware.io/janusweb/videoroomtest.html

According to your steps, I installed the Janus service locally 
./bin/janues 

settings obs stream url wss://janus1.cosmosoftware.io and 1234 for the room.
 streaming  
and how can i see  the obs stream in the web?

If I have any questions, please give me a specific step. Thank you.

**Comment by agouaillard-cosmo** [comment]
We could not reproduce your report. Actually, we could see you on the server when you tested.
Please try again, and feel free to open a new bug if you still can't connect following our instructions.

**Comment by myhuInShangHai** [comment]
local server video room plugin
![image](https://user-images.githubusercontent.com/20044086/39850311-32bcf6e8-5443-11e8-8a22-348631f72a4e.png)

obs settings ：
![image](https://user-images.githubusercontent.com/20044086/39850337-4f6a59ca-5443-11e8-95ad-4bbe6b0660cb.png)

when i want to see the stream：
![image](https://user-images.githubusercontent.com/20044086/39850365-8225dd1c-5443-11e8-8d8a-831f523deb65.png)

**Comment by agouaillard-cosmo** [comment]
please do not comment on close ticket. If you still have a problem, open a new bug. 
Make sure to provide enough information for us to reproduce the problem.
