### ISSUE TITLE
EBS: Settings/Stream replace the QComboBox list of codecs by a list of QRadioButtons

### ISSUE THREAD

**Issue by ludocosmo** [CoSMoSoftware/OBS-studio-webrtc#172]

**Comment by agouaillard-cosmo** [comment]
I checked on mac, and whatever I choose it ends up asking for VP8 ...

How to test:
run ebs from the terminal, from within the app/Contents/Ressource/Bin to get the log in the terminal
chose another codec (H264 or VP9),
click apply
click ok
click start streaming

you will see in the log the ack message from janus saying you requested VP8:
info: MESSAGE RECEIVED:
{
   "janus": "event",
   "session_id": 2020641725061942,
   "transaction": "162433302",
   "sender": 1284959510237536,
   "plugindata": {
      "plugin": "janus.plugin.lua",
      "data": {
         "publishers": [
            {
               "audio_codec": "opus",
               "display": "DrAlex",
               "id": "42b5d236-fa3d-4dfc-a068-9ae95132052d",
               "video_codec": "vp8"
            }
         ],
         "room": "7becfae6-65f3-48cb-9412-bc2548432225",
         "videoroom": "joined",
         "id": "EBS|42b5d236-fa3d-4dfc-a068-9ae95132052d",
         "attendees": [
            {
               "id": "42b5d236-fa3d-4dfc-a068-9ae95132052d",
               "display": "DrAlex"
            }
         ],
         "private_id": 1623361987
      }
   }
}

**Comment by agouaillard-cosmo** [comment]
fixed.
done.
