### ISSUE TITLE
Why when I install a local janus server I don t see myself on a different janus server?

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#18]
thanks
i have a question:

Configure JANUS
https://github.com/meetecho/janus-gateway. Configure a JANUS server using the video room plugin with websocket protocol activate. You can use their html demo.

OBS settings
Launch OBS, go to settings, select the stream tab and change the URL to your JANUS : wss://janus1.cosmosoftware.io
Put 1234 for the room.

After you can start streaming, OBS will connect to the default room and if you have any suscriber present in the room, you will see the OBS stream. https://clientweb.cosmosoftware.io/janusweb/videoroomtest.html

According to your steps, I installed the Janus service locally
./bin/janues

settings obs stream url wss://janus1.cosmosoftware.io and 1234 for the room.
streaming
and how can i see the obs stream in the web?

If I have any questions, please give me a specific step. Thank you.

**Comment by agouaillard-cosmo** [comment]
If you install a janus server locally, you need to:
1 - create the 1234 room in your local janus server
2 - create the corresponding access list
3 - point OBS to your local server, and *not* to cosmo's

Point 1 and 2 are explained in the Janus server documentation.
Point 3 is explained in our readme.

**Comment by myhuInShangHai** [comment]
thannks， i will be trying .
when i use the cosmo's server 

use video room demo:
![image](https://user-images.githubusercontent.com/20044086/39850624-f7728e84-5444-11e8-8a22-24bbb703cce9.png)

obs settings and stream
![image](https://user-images.githubusercontent.com/20044086/39850648-162c2d62-5445-11e8-8d60-097be68ab865.png)

open https://clientweb.cosmosoftware.io/janusweb/videoroomtest.html and input 1234 
![image](https://user-images.githubusercontent.com/20044086/39850674-3770c762-5445-11e8-8e9d-6dd3acb206b3.png)

i can't see the steam  .what wrong with me? 
I'm a novice, and I just want to see the obs stream. caould you tell me how i shoule do ？

**Comment by cosmo-rn** [comment]
You need to connect a webcam to your computer and authorize the access when prompted.

**Comment by myhuInShangHai** [comment]
i had done it , and then it appear the follow
![image](https://user-images.githubusercontent.com/20044086/39852286-3666225a-544e-11e8-9eaf-8c1a9ed1c216.png)

**Comment by myhuInShangHai** [comment]
I'll solve the problem thank you very much!!
