### ISSUE TITLE
EBS Mac: Base CPU usage seems to be higher on latest version

### ISSUE THREAD

**Issue by skastr0** [CoSMoSoftware/OBS-studio-webrtc#187]
All tests were executed through this guideline: https://docs.google.com/document/d/1NmRA1ePV92szB3fiI_jXMa6eo5k4H9l9kOwWO_s5CKU/edit?usp=sharing
Raw test data is included in two zip files.

[EBS Test - Castro - MacBook Pro 2018 - 10:17:2019.zip](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/3740087/EBS.Test.-.Castro.-.MacBook.Pro.2018.-.10.17.2019.zip)
[EBS Test - Castro - MacBook Pro 2013 - 10:17:2019.zip](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/3740089/EBS.Test.-.Castro.-.MacBook.Pro.2013.-.10.17.2019.zip)

They contain screenshots of hardware, base CPU usages of m65v22, m73v23 and m73v21 and OBS 24, 23.2.1, 23.1, 22.0.3. They also contain CPU usage when just previewing the input and streaming, for the EBS apps. CPU usage was collected through Activity Monitor. Input type used was Display Capture.

Initial impressions:
- There seems to be a distinct increase in CPU usage when the app is idle in EBS m73v23 when compared to every other EBS and OBS versions.
- When comparing m73v23 and m65v22, the increases in CPU when previewing the capture and streaming seems roughly equal.
- Conclusion 1: The difference in CPU usage between those two versions _might_ be caused by this increase in base cpu usage. Although the difference remains when streaming, it does not increase substantially.

- When comparing m73v23 and m73v21, the base CPU difference exists as well, m73v21 has a lower base cpu usage than m73v23.
- CPU usage when streaming on m73v21 tended to be much higher than the other two versions. Therefore, while it's true that the initial difference existed, it did not remain constant and the CPU usage of m73v21 ends up being the same as but tending to be higher than m73v23
- Conclusion 2: There seems to have been a visible improvement in CPU usage when streaming from m73v21 to m73v23.

**Comment by agouaillard-cosmo** [comment]
Test on MacBookAir 13" 2015:
![Screen Shot 2019-10-05 at 10 18 59 PM](https://user-images.githubusercontent.com/27793645/67028993-33355b80-f0c1-11e9-9bb3-d60dcc66a66e.png)

**EBS 1.4.x (m65v22),**
![Screen Shot 2019-10-17 at 9 19 29 AM](https://user-images.githubusercontent.com/27793645/67029049-5c55ec00-f0c1-11e9-83ac-ef25c2ec2528.png)

**EBS 2.3.0 (m73v23.2),**
![Screen Shot 2019-10-17 at 9 21 37 AM](https://user-images.githubusercontent.com/27793645/67029093-72fc4300-f0c1-11e9-8676-c1005a07f630.png)

**OBS 2.3.1.**
![Screen Shot 2019-10-17 at 9 30 58 AM](https://user-images.githubusercontent.com/27793645/67029134-86a7a980-f0c1-11e9-8be3-c6389d06bf23.png)

The CPU footprint seems stable at around 9~10% in the three cases. **Cannot Reproduce.**

Next: test on a MacBookPro 15" 2018

**Comment by agouaillard-cosmo** [comment]
Test on MacBookPro 2018:
<img width="265" alt="Screenshot 2019-10-17 at 9 38 52 AM" src="https://user-images.githubusercontent.com/27793645/67029537-5a405d00-f0c2-11e9-8bb2-fdbc7f8b289b.png">

**EBS m65v22:**
<img width="1255" alt="Screenshot 2019-10-18 at 6 06 25 AM" src="https://user-images.githubusercontent.com/27793645/67096691-849b2480-f16d-11e9-95fe-c0f9ccdf042f.png">

**EBS m73v23.2.0:**
<img width="1225" alt="Screenshot 2019-10-18 at 6 09 15 AM" src="https://user-images.githubusercontent.com/27793645/67097227-86b1b300-f16e-11e9-86db-1a78a59fb378.png">

**OBS v23.2.1:**
<img width="1151" alt="Screenshot 2019-10-18 at 6 17 57 AM" src="https://user-images.githubusercontent.com/27793645/67097507-1b1c1580-f16f-11e9-92c0-5ac3774f1cc4.png">

CAN REPRODUCE

Hyp. 1: different build
  => download build from shared repo and re-test MBP  
  => take the build from the MacBook Air and test on MBP
  => re-build latest code and re-test on MBP

Hyp. 1:  different hardware / OS

**Comment by agouaillard-cosmo** [comment]
Hyp. 1: different build
=> download build from shared repo and re-test MBP  == CAN REPRODUCE
=> take the build from the MacBook Air and test on MBP == CAN REPRODUCE

**Comment by agouaillard-cosmo** [comment]
=> re-build latest code and re-test on MBP == CAN REPRODUCE.

Trying Mac tools to trace where the CPU I being spent to see a difference, but it s the exact same app, running better on MacBook Air, and worse on Mac book Pro. That difference can only come from external factor. Instruments and sampling did not provide any obvious answer.

Now the difference with stock OBS might come from updated dependencies. (Hyp 2). We did not update the dependencies when we updated OBS, so there is a potential mismatch to investigate.

**Comment by agouaillard-cosmo** [comment]
<img width="699" alt="Screenshot 2019-10-18 at 3 21 07 PM" src="https://user-images.githubusercontent.com/27793645/67132213-ca330e00-f1bc-11e9-8347-bf89fb90b6fd.png">
<img width="669" alt="Screenshot 2019-10-18 at 3 30 56 PM" src="https://user-images.githubusercontent.com/27793645/67132214-cacba480-f1bc-11e9-96c2-3929087ecc8f.png">
<img width="668" alt="Screenshot 2019-10-18 at 3 33 42 PM" src="https://user-images.githubusercontent.com/27793645/67132215-cacba480-f1bc-11e9-82b9-8a4f55b9fcd4.png">

**Comment by agouaillard-cosmo** [comment]
From the trace of the execution of the three versions on a MacBook Pro, it s clear that:
- EBS m65v22 and OBS 23.2.1 have a similar runtime profile.
- EBS m73v23.2 is spending an enormous amount of time on an additional OpenGL thread that does not appear in the other two versions.

**Comment by agouaillard-cosmo** [comment]
New build by Ludo reduce the speed difference to less than the confidence interval. One of the main difference is that Ludo uses newer dependencies, e.g. QT 5.13 instead of 5.10.

<img width="1555" alt="Screenshot 2019-11-05 at 2 18 46 AM" src="https://user-images.githubusercontent.com/27793645/68171125-ce0fb000-ff72-11e9-8fbc-582bb3ffea16.png">

**Comment by agouaillard-cosmo** [comment]
fixed.
