### ISSUE TITLE
EBS Streams have 3 second freezes ONLY when receiving on a PC

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#190]
Like the title says, when streaming using the vp9 codec, anyone watching the stream on a PC (Chomre) will experience frequent 3 second freezes. If they are watching the stream on a Mac (Chrome), there are no 3 second freezes.

**Comment by agouaillard-cosmo** [comment]
Since the stream is playing fine with chrome on Mac suggest that:
- it is not a EBS problem
- it is not a chrome problem
- it is at best a chrome + windows problem.

**Comment by agouaillard-cosmo** [comment]
duplicate #161
