### ISSUE TITLE
EBS - Change UI element to enable testing of bitrates

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#194]
To add ability to change bitrate, KITE would need to control the UI element. Current UI element (Stepper) on Mac is not controllable. Can it be changed to "text edit" instead?

Originally reported by Hoang Vu.

**Comment by ludocosmo** [comment]
Settings/Output video bitrate: UI element QSpinBox has been replaced by a QLineEdit

BEFORE with QSpinBox:
![194_before_bitrate_text_edit](https://user-images.githubusercontent.com/30816985/69952292-dc30fc00-1531-11ea-900a-ef782df6f78e.png)

NOW with QLineEdit:
![194_after_bitrate_text_edit](https://user-images.githubusercontent.com/30816985/69952249-c28fb480-1531-11ea-9a20-332c98ac4a76.png)

**Comment by agouaillard-cosmo** [comment]
nam to confirm it made it testable.

**Comment by namvuCosmo** [comment]
confirmed
