### ISSUE TITLE
EBS [WINDOWS] crashed durring marathon test

### ISSUE THREAD

**Issue by namvuCosmo** [CoSMoSoftware/OBS-studio-webrtc#195]
KITE Marathon test
 - EBS + chrome + chrome
 - Codec:  vp9
 - Duration: 1hour

Crashed at around minute 55 .

ScreenShot:
![image](https://user-images.githubusercontent.com/27989546/70528677-ba66f300-1b89-11ea-9a71-500db47b0fcb.png)

Log:
[crash log.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/3944560/crash.log.txt)

**Comment by agouaillard-cosmo** [comment]
reworking the build system. open a new bug if it still happen after that.
