### ISSUE TITLE
JNS-Password protected room

### ISSUE THREAD

**Issue by tucsi** [CoSMoSoftware/OBS-studio-webrtc#198]
Hi!

Is it possible to stream to a password protected room ?
I couldn't find any solution to that.

Thanks,
Janos

**Comment by agouaillard-cosmo** [comment]
Hi tucsi,

depending on the service you choose, they can have password protected access 9room, url, ...) or not.

What were you trying to stream to?

**Comment by tucsi** [comment]
Hi,
Thank you for your answer.
Forgot to tell that I'm using Janus Streaming Server.
Thank you!

**Comment by agouaillard-cosmo** [comment]
We have only implemented support for the Janus VideoRoom signalling API.
If you want to support their streaming plugin, you need to implement the streaming plugin signalling.
For the [assword protection, you then better ask Lorenzo (miniero).

**Comment by tucsi** [comment]
VideoRoom signalling API is fine, because I'm using that plugin on Janus server. 
When you send the "join" request on websocket, you can add an optional "pin" parameter: that is the room password.
As far as I can see, you need to only add an extra input field in the settings window (room password) which will be sent on "joining" the room as "pin" parameter.

**Comment by agouaillard-cosmo** [comment]
Hi, I should spend some time on OBS next week, i ll try to squeeze this through.

**Comment by tucsi** [comment]
Wow, that would be cool, thank you! :)

**Comment by EquinoxQNX** [comment]
Hi,

I think it would be great if both pin and token (allowed string token) options added to join request.

**Comment by agouaillard-cosmo** [comment]
yep, let me finish the update to webrtc m79 and OBS 25, then i ll start unpiling.

**Comment by agouaillard-cosmo** [comment]
otherwise, PR are also welcomed :-)

**Comment by agouaillard-cosmo** [comment]
Update specific to janus server:

1. No support for Janus will be provided by default. Bruden of proof (that there is a bug on the OS Side) is on the one(s) opening the tickets.
2. There is no commercial support for this fork of OBS.
3. Janus support will only be done through the WHIP protocol.
4. Commercial support for Janus server side is available [here](https://janus.conf.meetecho.com/support).
