### ISSUE TITLE
websocket-client should not depend on libwebrtc but openssl

### ISSUE THREAD

**Issue by murillo128** [CoSMoSoftware/OBS-studio-webrtc#20]
https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/master/plugins/websocket-client/CMakeLists.txt#L15

**Comment by agouaillard-cosmo** [comment]
Mac:
- kept libwebrtc support in obs
- removed find_package libwebrtc in the web socket dll target
- replaced it with find package (openssl)
- validated by:
  -- compiles
  -- streamed against janus and millicast and check on their respective web client i could receivee the stream.

**Comment by agouaillard-cosmo** [comment]
still ongoing work on windows. It does not compile as of yet, thanks to windows DLL HELL.

**Comment by agouaillard-cosmo** [comment]
Done. Validated only on Mac.
