### ISSUE TITLE
EBS: Linux installation package

### ISSUE THREAD

**Issue by ludocosmo** [CoSMoSoftware/OBS-studio-webrtc#200]
- sh self extracting wrong CPack generator for Linux
- default installation path is not in /usr/local but in <current_dir>/usr/local
- ffmpeg libraries are not included
- Qt libraries are not included

**Comment by agouaillard-cosmo** [comment]
update: ffmpeg not included and Qt not included in the package is expected, and mimic the original OBS installer.

**Comment by agouaillard-cosmo** [comment]
update: going for debian package

**Comment by agouaillard-cosmo** [comment]
delivered.
