### ISSUE TITLE
How to connect to Jitsi

### ISSUE THREAD

**Issue by Exellent1988** [CoSMoSoftware/OBS-studio-webrtc#203]
Hy is there a Way to connect to a Jisty Server its also a Webrtc server, but i cant fiure out how to use  this obs version to connect to our server ( auth is off)

**Comment by agouaillard-cosmo** [comment]
On paper, there is no problem. The media stack is already here, you just need to support jitsi signalling.
Practically, in /plugin/obs-output, you need to add a class to implement jitsi like you have a class for janus, evercast, millicast (the xxxStream class), and then wire it in the logic and the UI.

**Comment by sm2x** [comment]
very interested in this feature also, is jitsi signaling documented somewhere to adapt to one of the existing implementations?

**Comment by agouaillard-cosmo** [comment]
@sm2x I believe this is a question for the jitsi team.

**Comment by agouaillard-cosmo** [comment]
I think the original question has been answered. If there is still questions, please open a new bug.
