### ISSUE TITLE
NDI Plugin support

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#204]
* using the last OBS Studio version available.
 * install an additional plugin called "obs-ndi",
=> no NDI sources or outputs.

**Comment by agouaillard-cosmo** [comment]
1. what version of OBS did you use, and on what platform?
OBS Studio 25.0.4 with the plugin OBS-NDI 4.7.1 installed

2. please provide the link to the corresponding OBS installer.
https://cdn-fastly.obsproject.com/downloads/OBS-Studio-25.0.4-Full-Installer-x64.exe / https://github.com/Palakis/obs-ndi/releases/download/4.7.1/obs-ndi-4.7.1-Windows-Installer.exe

3.What NDI device did you use for input, res. output?
I'm putting a 1080p 30 FPS out of a MIMO Live instance, I'd capture it in OBS with the NDI Source option (not available in the WebRTC modified version)

4.Can you provide screenshot of NDI related settings, and what you are expecting to see / seeing with vanilla OBS?
I will need to put the setup on again, I will do this tomorrow and provide you with the screenshots

5. can you provide the same screenshoots illustrating the problem on millicast-OBS?
Same again like the previous question, I will do the same setup and provide you with all the details.

**Comment by agouaillard-cosmo** [comment]
Blocked on #217

**Comment by agouaillard-cosmo** [comment]
Now blocked on #225

**Comment by agouaillard-cosmo** [comment]
That will be achieved in v26

**Comment by torinmb** [comment]
were you able to get the NDI plugin to install? This would be incredibly useful. Thanks!

**Comment by agouaillard** [comment]
This will be achieved in v26. A few more weeks.

**Comment by agouaillard-cosmo** [comment]
this is now available in v26 alpha 2.
