### ISSUE TITLE
Directory for libwebrtc

### ISSUE THREAD

**Issue by kfvk** [CoSMoSoftware/OBS-studio-webrtc#205]
Working on building OBS-studio-webrtc on Lubuntu 18.04. 

libwebrtc-audio-processing is included in the current package repository. Is this the same package required by OBS-studio-webrtc? The Lubuntu repository package doesn't seem to include either of the

libwebrtcConfig.cmake
libwebrtc-config.cmake

files referred to in the error output (given below). If it is indeed able to work with OBS-studio-webrtc, I'm unclear on where/proper syntax to include the path in the plugins/obs-output/CMakeLists.txt file, as it is installed in a number of locations:

/usr/lib/x86_64-linux-gnu/libwebrtc_audio_processing.so.1.0.0
/usr/share/doc/libwebrtc-audio-processing1
/usr/lib/x86_64-linux-gnu/libwebrtc_audio_processing.so.1
/usr/include/webrtc_audio_processing/webrtc
/usr/lib/x86_64-linux-gnu/libwebrtc_audio_processing.a
/usr/share/doc/libwebrtc-audio-processing-dev

If libwebrtc should be compiled from source, I've what appear to be common issues there as well but will post on the proper forum to resolve those. 

The error message:

CMake Error at plugins/obs-outputs/CMakeLists.txt:31 (find_package):
  By not providing "Findlibwebrtc.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "libwebrtc", but CMake did not find one.

  Could not find a package configuration file provided by "libwebrtc"
  (requested version 69) with any of the following names:

    libwebrtcConfig.cmake
    libwebrtc-config.cmake

  Add the installation prefix of "libwebrtc" to CMAKE_PREFIX_PATH or set
  "libwebrtc_DIR" to a directory containing one of the above files.  If
  "libwebrtc" provides a separate development package or SDK, be sure it has
  been installed.

Thanks so much!

**Comment by agouaillard-cosmo** [comment]
hi kfvk,

The CMake `find_package` documentation gives you information about the CONFIG mode:
https://cmake.org/cmake/help/latest/command/find_package.html#full-signature-and-config-mode

I think the answer to your question can be found in the wiki:
https://github.com/CoSMoSoftware/OBS-studio-webrtc/wiki/Build

**Comment by kfvk** [comment]
Thank you!! I've read through those and am still struggling, but I'm a bit over my head in this project. I'll keep going and see what comes out of it. Thanks!
