### ISSUE TITLE
 How do I solve the following problem?

### ISSUE THREAD

**Issue by thoopring** [CoSMoSoftware/OBS-studio-webrtc#207]
CMake Error at plugins/websocket-client/CMakeLists.txt:22 (add_subdirectory):
  The source directory

    E:/OBS-studio-webrtc/plugins/websocket-client/nlohmann_json

  does not contain a CMakeLists.txt file.

**Comment by SCG82** [comment]
git submodule update —init —recursive 

(note those are two - dashes in front of init & recursive)
