### ISSUE TITLE
EBS - Default Video Settings

### ISSUE THREAD

**Issue by namvuCosmo** [CoSMoSoftware/OBS-studio-webrtc#208]
Hi,

Going through the result of KITE regression test for Windows, I noticed a failure for the Default Video Settings verification step:
![image](https://user-images.githubusercontent.com/27989546/79536329-637ea680-80b2-11ea-9a56-08d11a1b0406.png)

The expected value for down-scaling is : `Bilinear (Fastest but blurry if scaling)`
The actual value from test is : `Bicubic (Sharpened scaling, 16 samples)`

link to binary [here](http://file-server.cosmosoftware.io:8080/FileServer/downloadServlet?fileName=EBS-WINDOWS.zip)

Is this a new change?

**Comment by agouaillard-cosmo** [comment]
The latest EBS code has not been merged back, so we don't know the current status of EBS.
It looks like this commit address this question, though:
https://github.com/evercast/evercast-broadcaster-software/commit/8fc9bde8901f060ccf728f29274f262921ad8e11
