### ISSUE TITLE
EBS - Auto Update pop-up

### ISSUE THREAD

**Issue by namvuCosmo** [CoSMoSoftware/OBS-studio-webrtc#209]
Hi,

Is there a way that you can disable the Update pop-up in the app?

I know it only pops up the first time opening the binary, but if we want to test new binaries every now and then, this will happen all the time.

If there's no way then I will modify the test to look for that update pop-up, but it might be tricky.

**Comment by agouaillard-cosmo** [comment]
it looks like it s being addressed. reopen if a problem.
