### ISSUE TITLE
MC - implement millicast as a media source

### ISSUE THREAD

**Issue by wesleystrikes** [CoSMoSoftware/OBS-studio-webrtc#210]
customer request

**Comment by agouaillard-cosmo** [comment]
it looks like an easy way would be to use the browser source in OBS.
that requires a build with CEF enabled, which I believe is not the case with the millicast build.

**Comment by SCG82** [comment]
The builds on the download page (https://dash.millicast.com/docs.html?pg=obs-with-millicast <https://dash.millicast.com/docs.html?pg=obs-with-millicast>) contain all the plugins that OBS v23.2 has, including the browser source.

**Comment by agouaillard-cosmo** [comment]
To test.

**Comment by agouaillard-cosmo** [comment]
@wesleystrikes media source to ... what?
If it is for an SDI display, the Millicast Player would be better.
Depending on the use case, the solution will differ.

**Comment by agouaillard-cosmo** [comment]
duplicate #237
