### ISSUE TITLE
Track breaking problem

### ISSUE THREAD

**Issue by thoopring** [CoSMoSoftware/OBS-studio-webrtc#211]
Hi developers.
I respect your skills very much.
There was a problem during Video Tessing with OBS-studio-webrtc and Janus.
When video/audio is sent to webrtc, 'event.track.onend' events occur frequently. And the log of Janus.log ("Remote track mated/removed:" ev);" also continues to appear in the Console. Please make sure this is OBS-studio-webrtc's bug. Also, I would appreciate it if you could tell me how to solve it.

**Comment by agouaillard-cosmo** [comment]
Hi thoopring. 
Can you tell us more about your setup so we can try to reproduce your problem?

**Comment by thoopring** [comment]
'The problem was solved when using the Janus video plugin room.' I am using OBS-studio WebRTC version 21.0.3.

We are using 'videoroomtest' among demos provided by JANUS server installed on Linux.

I confirmed that the 'OBS' Video screen is displayed in 'videoroomtest.html', but it does not last, and the 'Remote track' event occurs periodically.
That is, the OBS screen is displayed and is not displayed repeatedly.

**Comment by agouaillard-cosmo** [comment]
I'm confused. Was the problem solved or not?

**Comment by thoopring** [comment]
Problem solved.
Attach the reference image.

[Well done]
![image](https://user-images.githubusercontent.com/8147160/80183470-d902ed80-8643-11ea-836b-6ca56ed9bc3f.png)

[Not good]
![image](https://user-images.githubusercontent.com/8147160/80183699-3e56de80-8644-11ea-804d-e4b0752d2728.png)


The above situation is repeated.

**Comment by agouaillard-cosmo** [comment]
ok. Closing, marked as solved.
