### ISSUE TITLE
JNS - add string room id support

### ISSUE THREAD

**Issue by EquinoxQNX** [CoSMoSoftware/OBS-studio-webrtc#218]
Several months ago Janus started to support string room id. 

https://github.com/meetecho/janus-gateway/pull/1880

I've got following error when I try this app with string id.

![image](https://user-images.githubusercontent.com/49026539/83092868-f3970f00-a0a6-11ea-9e57-a42e0d3080c5.png)

![image](https://user-images.githubusercontent.com/49026539/83092805-c5193400-a0a6-11ea-9b0c-7d6b024cf602.png)

**Comment by agouaillard-cosmo** [comment]
Was it working with numerical IDs?

**Comment by agouaillard-cosmo** [comment]
Update specific to janus server:

1. No support for Janus will be provided by default. Bruden of proof (that there is a bug on the OS Side) is on the one(s) opening the tickets.
2. There is no commercial support for this fork of OBS.
3. Janus support will only be done through the WHIP protocol.
4. Commercial support for Janus server side is available [here](https://janus.conf.meetecho.com/support).
