### ISSUE TITLE
RFS - Blackmagic cards / drivers not recognised or available for use

### ISSUE THREAD

**Issue by alex-hijack** [CoSMoSoftware/OBS-studio-webrtc#222]
build 10.0.05

**Comment by agouaillard-cosmo** [comment]
Hi Alex. 
Thanks for the ticket.
Was it working in a previous version? If yes, which one?
Which blackmagicdesign card did you test with?
On which Apple device and OS did you experience the problem?

**Comment by alex-hijack** [comment]
Hi Alex,

Hope all is good.

Yes, it's working on all other versions including OBS-WebRTC and for all the Ultrastudio family cards, Express, Mini recorder, Ultrastudio 4K etc.. It’s what we have been using for all our testing.

When 'Blackmagic Desktop Video' drivers are installed it is its own choice under ‘Sources’ even without a card plugged in. It has also been working fine on RFS 10.0.1 - 10.0.4, so just the latest version it doesn’t show.

See screen shots attached. That is the same system and the Blackmagic card isn’t available as a selection in 10.0.5. I also don’t get a choice under ‘Video Capture Device'

Let me know if you need any further info, screen shots etc...

Best

Alex






Alex Seery

HIJACK
Markian House
52-56 Pritchards Road
London, E2 9AP

T +44 (0) 207 205 4425
alex@hijackpost.com
hijackpost.com

COLOUR | AUDIO | ONLINE | DELIVERABLES | DIT

**Comment by agouaillard-cosmo** [comment]
https://gist.github.com/DDRBoxman/334cec50d8e5045b836f3f8e95691d50

**Comment by agouaillard-cosmo** [comment]
confirmed, the entitlement was the key. Th new build 10.0.6 seems to address the problem. @alex-hijack , ready for validation.

**Comment by alex-hijack** [comment]
Issue fixed in v10.0.6, tested on several computers.
Many thanks
