### ISSUE TITLE
Websocket availability?

### ISSUE THREAD

**Issue by patrickcusack** [CoSMoSoftware/OBS-studio-webrtc#227]
I see that the current version of OBS-webRTC has a websocketclient.dylib that loads, but I don't see any websockets created when running from the command line. I installed the 23.2 compatible 4.7.0 web socket plugin (https://github.com/Palakis/obs-websocket/releases/tag/4.7.0) but that doesn't work either. Otherwise, when running the current version of plain OBS, I see websockets instantiated on in the logs.

**Comment by agouaillard-cosmo** [comment]
See #228
