### ISSUE TITLE
Setup releases on github to be able download assets

### ISSUE THREAD

**Issue by kindermax** [CoSMoSoftware/OBS-studio-webrtc#230]
Hi, It would be great to have the ability to download assets from github releases page. 

For now the latest released version is https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.8.

**Comment by agouaillard-cosmo** [comment]
Yes, that would be nice. I'm adding it to the todo list.

**Comment by agouaillard-cosmo** [comment]
done.

**Comment by kindermax** [comment]
Wow, that is amazing! Thank you.
