### ISSUE TITLE
Ant Media Support

### ISSUE THREAD

**Issue by jensJJ** [CoSMoSoftware/OBS-studio-webrtc#233]
Hello,

I would like to ask, if it is also compatible with Ant Media Enterprise v2.1.
I tried it entering my wss (websocket) path but OBS WebRTC cant connect to it.

Thanks

**Comment by agouaillard-cosmo** [comment]
Hi,
No it is not for now.
You can either try to stream out RTMP, or modify the source code to add ant media signalling part.

More information here: https://github.com/CoSMoSoftware/OBS-studio-webrtc/wiki

**Comment by Mitsuma** [comment]
Any plans on adding it? You wrote "not for now", feels like it implies its planned.

**Comment by agouaillard-cosmo** [comment]
Hi mitsuma.

Please do not add comments on closed tickets.

"not now" meant to confirm that the user was not doing anything wrong, it was not expect to work.

My answer to you will be the same in nature as the previous one: if you want it, go ahead and implement it yourself.
