### ISSUE TITLE
OBS macOS can segfault when using another app in the foreground 

### ISSUE THREAD

**Issue by patrickcusack** [CoSMoSoftware/OBS-studio-webrtc#238]
I think this is RC2. The version that has WHIP support. 

OBS crashes in what appears to be a hot key handler on macOS 10.15.6. See attached crash reports:
Thread 1 Crashed:
0   com.apple.iokit.IOHIDLib      	0x000000001016e6ed 0x10161000 + 55021
1   com.apple.iokit.IOHIDLib      	0x000000001016f267 0x10161000 + 57959
2   com.apple.framework.IOKit     	0x00007fff349567fd IOHIDDeviceGetValue + 33
3   libobs.0.dylib                	0x000000010f12d7bd obs_hotkeys_platform_is_pressed + 205
4   libobs.0.dylib                	0x000000010f1473d0 obs_hotkey_thread + 224
5   libsystem_pthread.dylib       	0x00007fff6bb63109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6bb5eb8b thread_start + 15

If you start OBS and don't touch anything on the system, the issue doesn't happen. This hasn't occurred 
in the July 14th build. But I'm not likely running those on the latest Catalina release (10.15.6) either.

[Archive.zip](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5276181/Archive.zip)

**Comment by agouaillard-cosmo** [comment]
merged into #250
