### ISSUE TITLE
Please add support for definable Millicast publishing endpoint 

### ISSUE THREAD

**Issue by patrickcusack** [CoSMoSoftware/OBS-studio-webrtc#239]
I would like to test OBS on a segmented Millicast cloud instance. Can you please include a facility to define a custom publishing endpoint?

**Comment by agouaillard-cosmo** [comment]
@ludocosmo 
Can you please, after project Emmet, 
- branch out m84v23.2,
- add one "Simulcast" check box to all webrtc setting panels (Sergio will do the logic),
- add one field specific to the millicast setting UI to expose the URL variable, then wire it through.
Today the URL is hardcoded in `plugins/websocket-client/MillicastWebsocketClientImpl.cpp`, it would be better to have a field, populated by default in the UI, and percolate the value down like it used to be. See commented out lines in `vendor_skins/RemoteFilming/plugins/rtmp-services/webrtc-millicast.c`

**Comment by agouaillard-cosmo** [comment]
won't fix.
