### ISSUE TITLE
OBS reports 0KB/s when using webrtc

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#24]
romain, can you investigate this? likely the webrtc bandwidth estimation or corresponding stat (better) is not wired with the UI or tool.

**Comment by cosmo-rn** [comment]
problem fixed

**Comment by agouaillard-cosmo** [comment]
wait, how did you fix it, and how to check/validate it? I on; t see any commit referenced here.
( to have a commit appear in a ticket thread insert the ticket number in the commit message. For this ticket it would mean e.g. adding a #24 at the end of the commit message).

**Comment by agouaillard-cosmo** [comment]
Note for romain: since this is a bug, you should use [FIX] and not [ENH].
commit 35b01b6
@bogenpirat can you kindly check if this address the problem you originally reported?

**Comment by bogenpirat** [comment]
@agouaillard-cosmo Thanks for the heads up. Unfortunately I'm unable to test this right now as I've run into some trouble setting up the toolchain for compilation. The server/consumer end are set up though, so if you happen to have time to compile a binary, I'd love to report back how it performs.

**Comment by agouaillard-cosmo** [comment]
@cosmo-rn can you prepare a release in https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases

**Comment by cosmo-rn** [comment]
The release is now available.
https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.0

**Comment by cosmo-rn** [comment]
Sorry for the wait. The release is now available.
https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.0

**Comment by bogenpirat** [comment]
I can report that bandwidth displays properly.

**Comment by agouaillard-cosmo** [comment]
Thanks for validating.
