### ISSUE TITLE
h264 to Firefox  no video only audio

### ISSUE THREAD

**Issue by rnkvogel** [CoSMoSoftware/OBS-studio-webrtc#241]
Firefox using H264 codec will have black screen on viewer. 
V8 and VP9 does work on Firefox.  Millicast web based publisher using h264 is able to publish to Firefox successfully.

**Comment by agouaillard-cosmo** [comment]
== Sender side ==
Streaming using OBS <VERSION>,
on Desktop OS <OS_NAME, OS_REV>,
using <INPUT>, <CODEC>, <SETTINGS>....

== receiver side ==
trying to display the stream using <APP>,
[ in <BROWSER, BROWSER_REV>, ]
on <OS_NAME, OS_REV>,

== Symptoms ==
No video displayed.

== Expectation ==

**Comment by agouaillard-cosmo** [comment]
Used millicast's OBS-studio-webrtc m84v23.2 RC2 on Mac.
Default settings,
Stream to millicast.
- using H264, I can see the stream in Chrome, but not in firefox, both desktop versions, both on Mac.
- using VP8 I can see the stream in both Chrome and Firefox, both desktop versions, both on Mac.

- I checked the O/A on both sides and could don't spot anything suspicious or different.
- I checked about:webrtc and chrome://webrtc-internals, respectively, and nothing was out of the ordinary. Actually firefox showed 200+ Kbps video packets being delivered. It is lower than what we were expecting if it was working (OBS shows 2+ Mbps, chrome receives 2+ Mbps) but in the absence of any video being displayed I was expecting 0. 
- I checked Firefox bug tracker for any outstanding bugs and could not find any.

@murillo128  will need to jump in for that one.

**Comment by murillo128** [comment]
What's weird is that if I start broadcasting in chrome and then switch to OBS, the OBS stream is played correctly on firefox.

I can't get the webrtc traces in Firefox for windows. Will investigate it further.

**Comment by agouaillard-cosmo** [comment]
OBS is sometimes not pushing the codec name correctly.

The first function below needs to be modified to force the codec to H264 when video_codec is empty.
The second function needs to make sure video_codec is NEVER empty (with error message).

void WebRTCStream::OnSuccess(webrtc::SessionDescriptionInterface *desc)
{   
    info("WebRTCStream::OnSuccess\n");
    std::string sdp;
    desc->ToString(&sdp);
    audio_codec = "opus";
    video_codec = video_codec.empty() ? "" : video_codec.c_str()
    
    info("Audio codec:      %s", audio_codec.c_str());
    info("Audio bitrate:    %d\n", audio_bitrate);
    info("Video codec:      %s", y() ? "Automatic" : video_codec.c_str());
    info("Video bitrate:    %d\n", video_bitrate);
    info("OFFER:\n\n%s\n", sdp.c_str());
    
    std::string sdpCopy = sdp;
    if (type == WebRTCStream::Type::Wowza) {
    }
    
    info("SETTING LOCAL DESCRIPTION\n\n");
    pc->SetLocalDescription(this, desc);
    
    info("Sending OFFER (SDP) to remote peer:\n\n%s", sdpCopy.c_str());
    client->open(sdpCopy, video_codec, username);
}


bool MillicastWebsocketClientImpl::open(
        const std::string & sdp,
        const std::string & video_codec,
        const std::string & audio_codec,
        const std::string & stream_name)
{
    info("WS-OPEN: stream_name: %s", stream_name.c_str());
    try {
        json data_without_codec = {
            { "name", sanitizeString(stream_name) },
            { "streamId", sanitizeString(stream_name) },
            { "sdp" , sdp }
        };
        json data_with_codec = {
            { "name", sanitizeString(stream_name) },
            { "streamId", sanitizeString(stream_name) },
            { "sdp" , sdp },
            { "codec", video_codec }
        };
        // Publish command (send offer)
        json open = {
            { "type", "cmd" },
            { "name", "publish" },
            { "transId", rand() },
            { "data", video_codec.empty() ? data_without_codec : data_with_codec }
        };

@ludocosmo can you take care of it and revalidate?

**Comment by ludocosmo** [comment]
Source of the problem: spelling of "H264"
Uppercase "H264": not recognized by Firefox, no video.
Lowercase "h264": recognized by Firefox, video displayed.

**Comment by agouaillard-cosmo** [comment]
RC3 fixes that:
https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.11
