### ISSUE TITLE
Obs studio crash on every restart WebRTC server

### ISSUE THREAD

**Issue by mdorofeev** [CoSMoSoftware/OBS-studio-webrtc#242]
Hi,

We have problem with obs studio crashes on every restart WebRTC server or internet connection lost.

How reproduce:

1. Start stream WebRTC to Wowza server
2. Restart server

Version: m84v23.2 RC 1
WebRTC server: Wowza

Crash report:
[Crash 2020-09-29 09-58-32.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5297057/Crash.2020-09-29.09-58-32.txt)

**Comment by agouaillard-cosmo** [comment]
Sorry, we do not support wowza server, it's a third party contributed implementation so you're on your own.
