### ISSUE TITLE
Upgrading to OBS v26

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#244]
Stephane taking care of it.

**Comment by phedders** [comment]
Just how progress is on this merge?

**Comment by agouaillard-cosmo** [comment]
It should be done before Xmass, keep some room under the tree ;-)

What's your interest in obs-studio-webrtc?

**Comment by phedders** [comment]
I'm wanting to stream a church service to a carpark full of people with mobile devices with as little latency or at least latency offset as possible. This paired with Janus looks like a great option to try.
Already using OBS 26... 
Is there a branch I can help test? 
Also is there a plan to push this upstream to the OBS-Studio repo?

**Comment by agouaillard-cosmo** [comment]
as of tuesday 22nd, the m84v26 builds are green, and the OBS binaries have been tested against millicast.

You can follow the test developments here:
https://github.com/agouaillard/OBS-studio-webrtc/tree/m84-v26.0-automated-builds

You can see the CI/CD here:
https://github.com/Palakis/OBS-studio-webrtc/pull/1

We expect first beta builds to be available on 24th (singapore), i.e. within 48 hours.
Before we remove the Beta status of the build, we want to integrate and automate our test suite that was so far separated in the repository.

@phedders we have tried to contribute the code back to OBS, made patches and proposed, but have failed to get enough traction so far.

**Comment by agouaillard-cosmo** [comment]
Now available.

https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.13
