### ISSUE TITLE
connection timed out issue when testing against janus

### ISSUE THREAD

**Issue by aet** [CoSMoSoftware/OBS-studio-webrtc#246]
[obs-webrtc.log](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5360564/obs-webrtc.log)
Hi! I was testing RC1 release build on macOS 10.15 Catalina using a custom docker setup running with Janus v0.10.6 and websocket/https handling offloaded to NGINX reverse proxy.

The built-in demos have been modified to use wss://testhost.local/ws/janus and they work out ok

So far I haven't been able to use OBS-WebRTC against Janus no matter what I do, running into this error message (see the attached file for the whole log)

19:32:51.175: CONNECTING TO wss://testhost.local/ws/janus
19:32:51.175: (openssl_certificate.cc:109): Returning certificate
19:32:51.175: 
19:32:51.175: (webrtc_session_description_factory.cc:481): Setting new certificate.
19:32:51.175: 
19:32:51.179: > set_fail_handler > handleFail called
19:32:51.179: Connection Timed out
19:32:51.179: WebRTCStream::onDisconnected
19:32:51.180: (peer_connection.cc:4794): Session: 7768793127408706324 Old state: kStable New state: kClosed

Not sure if there's extra webrtc specific logging to enable on OBS side, any idea what could be missing? The self-signed certificate is part of the keychain and set to trusted, and has been added to OpenSSL's cert.pem for testing sake (both /etc/ssl/cert.pem and /usr/local/etc/openssl*/cert.pem that the RC1 build has references against)

**Comment by aet** [comment]
@agouaillard-cosmo testing against wss://janus.conf.meetecho.com/ws goes through the step above but I can't be sure if it's the same version (0.10.6), Start Streaming button state remains "blank", logs keep spamming about keep-alive message repeatedly, but bottom status bar of OBS doesn't indicate the streaming actually is initialized.

Is Janus backend expected to work with RC1, which version is verified to work?

**Comment by agouaillard-cosmo** [comment]
Update specific to janus server:

1. No support for Janus will be provided by default. Bruden of proof (that there is a bug on the OS Side) is on the one(s) opening the tickets.
2. There is no commercial support for this fork of OBS.
3. Janus support will only be done through the WHIP protocol.
4. Commercial support for Janus server side is available [here](https://janus.conf.meetecho.com/support).
