### ISSUE TITLE
Questions about p2p usage, and usage against other webrtc servers.

### ISSUE THREAD

**Issue by lizardpeter** [CoSMoSoftware/OBS-studio-webrtc#247]
Hello,

This is a very nice software and something I would love to see in the official OBS build. However, I am struggling to understand how to use custom webRTC implementations with it. How would I go about setting up a peer-to-peer connection or stream webRTC to a server other than the ones in the options? Also, does anyone know of any webRTC servers that are free and work on Windows?

Thanks,
Peter

**Comment by agouaillard-cosmo** [comment]
hi Peter.

**p2p**
- streaming out to another webrtc peer is likely not an option.
- streaming in from a peer could be done through the browser source.

**using other server**
- add support for that server specific signalling.
- use a server that supports WHIP through the "custom webrtc server" option. 
https://datatracker.ietf.org/doc/draft-murillo-whip/

I do not free webrtc servers for windows.

We obviously recommend you to use this with the millicast platform for best performances.

**Comment by lizardpeter** [comment]
Thanks for the information. I tried installing Janus to do some testing, but I received the error "[FATAL] [dtls.c:janus_dtls_load_keys:302] Error opening key file." Do you know how to fix this?

**Comment by agouaillard-cosmo** [comment]
Update specific to janus server:

1. No support for Janus will be provided by default. Bruden of proof (that there is a bug on the OS Side) is on the one(s) opening the tickets.
2. There is no commercial support for this fork of OBS.
3. Janus support will only be done through the WHIP protocol.
4. Commercial support for Janus server side is available [here](https://janus.conf.meetecho.com/support).
