### ISSUE TITLE
Any information on duplicate symbol errors (MD5) from librtmp and libwebrtc?

### ISSUE THREAD

**Issue by alexciarlillo** [CoSMoSoftware/OBS-studio-webrtc#249]
Apologies if this is the wrong place to ask but I have a feeling if anyone has run into this, you have. When googling this I actually found Alex posting on a similar question [here](https://groups.google.com/g/discuss-webrtc/c/jA0RPgJi8uo) and thought maybe he might have found an answer on his own.

I am getting the following error when building my project on OS X 10.15

```
duplicate symbol '_MD5_Init' in:
    CMakeFiles/obs-outputs.dir/librtmp/md5.c.o
    /Users/alexciarlillo/code/src/googlesource/webrtc-checkout/src/out/m84/obj/libwebrtc.a(bcm.o)
duplicate symbol '_MD5_Final' in:
    CMakeFiles/obs-outputs.dir/librtmp/md5.c.o
    /Users/alexciarlillo/code/src/googlesource/webrtc-checkout/src/out/m84/obj/libwebrtc.a(bcm.o)
duplicate symbol '_MD5_Update' in:
    CMakeFiles/obs-outputs.dir/librtmp/md5.c.o
    /Users/alexciarlillo/code/src/googlesource/webrtc-checkout/src/out/m84/obj/libwebrtc.a(bcm.o)
ld: 3 duplicate symbols for architecture x86_64
```

My project is slightly different and not a direct fork of yours, but it takes a lot from the excellent work you have done. I am basing this off OBS 26 and trying to use my own libwebrtc build (targeting m84) and I am using FindLibWebRTC.cmake to accomplish this. And I think I am quite close to actually getting something compiled! 

I am building libwebrtc using the following:

```
gn gen out/m84 --args='is_debug=false is_component_build=false is_clang=true rtc_include_tests=false rtc_use_h264=true use_rtti=true mac_deployment_target="10.11" use_custom_libcxx=false'
```

I have slightly modified `FindLibWebRTC.cmake` to not add the boringssl headers, as another dependency is using openssl and I will be using that dependency for my webrtc signaling. 

```
set(LIBWEBRTC_INCLUDE_DIRS
		${WEBRTC_INCLUDE_DIR}
		${WEBRTC_INCLUDE_DIR}/third_party
		${WEBRTC_INCLUDE_DIR}/third_party/abseil-cpp
		${WEBRTC_INCLUDE_DIR}/third_party/libyuv/include
		# ${WEBRTC_INCLUDE_DIR}/third_party/boringssl/src/include
	)
```

And I have modified the cmake command to the following, disabling many of the bits I will not need and override some variables to fix things on my platform.

```    
cmake -DENABLE_SPARKLE_UPDATER=OFF \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
        -DDISABLE_PYTHON=ON  \
        -DQTDIR="/tmp/obsdeps" \
        -DSWIGDIR="/tmp/obsdeps" \
        -DDepsPath="/tmp/obsdeps" \
        -DVLCPath="${DEPS_BUILD_DIR}/vlc-${VLC_VERSION:-${CI_VLC_VERSION}}" \
        -DCMAKE_USE_OPENSSL=ON \
        -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1h \
        -DOPENSSL_CRYPTO_LIBRARY=/usr/local/Cellar/openssl@1.1/1.1.1h/lib/libcrypto.1.1.dylib \
        -DWEBRTC_ROOT_DIR=/Users/alexciarlillo/code/src/googlesource/webrtc-checkout \
        -DMEDIASOUPCLIENT_BUILD_TESTS=OFF \
        -DBUILD_BROWSER=OFF \
        -DBROWSER_DEPLOY=OFF \
        -DBUILD_CAPTIONS=OFF \
        -DWITH_RTMPS=OFF \
        -DCEF_ROOT_DIR="${DEPS_BUILD_DIR}/cef_binary_${CEF_BUILD_VERSION:-${CI_CEF_VERSION}}_macosx64" \
        ..
```

My end goal is to create an output that is compatible with the [mediasoup project](https://mediasoup.org/) using their C++ client library and would be happy to contribute back anything of worth I end up creating.

I completely understand if my environment is too different for you to take the time. I just thought maybe you have seen similar issues and might have a hint to put me on the right path.

Thanks!

**Comment by agouaillard** [comment]
Given that we provide our OBS-studio with an implementation of WHIP, the easiest way for you to do what you want to do is to implement WHIP on the media soup side, and just use our precompiled binaries for OBS-Studio-webrtc.
http://webrtcbydralex.com/index.php/2020/09/30/whip-make-webrtc-easy-to-use-for-media-platforms-ingest/

**Comment by alexciarlillo** [comment]
Fair enough. Unfortunately implementing WHIP on the mediasoup side is less straightforward as our server-side application (which is built on mediasoup-server) has a fair bit of application-specific signaling built in to at the moment beyond just pure media ingestion. mediasoup-server is signaling-agnostic so a WHIP implementation is definitely worth pursuing, just out of scope of our current project goals. We are currently more in the "discovery" phase of answering the question: can we get OBS captured video into our application as-is? I feel like I am very close to being able to answer that question - and then do the work to improve and stabilize _how_ we do it. But implementing WHIP just to answer this would be putting the cart before the horse.

Out of curiosity, I noticed you commented out librtmp/md5.h here: https://github.com/CoSMoSoftware/OBS-studio-webrtc/commit/c651fe5985ba9edec0363bff4ed20b9fbc805360 which looks very similar to what I am doing with using openssl. Just wondering if you ran into the same thing and this was a quick fix to get it compiling.

**Comment by alexciarlillo** [comment]
FYI commenting out "librtmp.c" did clear up the error. It finally built after 3 days of frustration!

Just a heads up for your OpenSSL work - on OSX 10.15, find_package(OpenSSL) does not find the correct libcrypto (installed from homebrew openssl) it still attempts to use the system one and you get errors about your application not being allowed to link to it. You may see something like:

```
Linking C shared library ../../../../lib/libcurl.dylib ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib
```

I found that you can override the path to the library directly using `-DOPENSSL_CRYPTO_LIBRARY`. Specifically for my case: `-DOPENSSL_CRYPTO_LIBRARY=/usr/local/Cellar/openssl@1.1/1.1.1h/lib/libcrypto.1.1.dylib \` there may be a more preferable path to use, but that gets the job done for me for now.

Hope this might save you a headache, it's the least I can do! Thanks for your time!

**Comment by SCG82** [comment]
> Just a heads up for your OpenSSL work - on OSX 10.15, find_package(OpenSSL) does not find the correct libcrypto (installed from homebrew openssl) it still attempts to use the system one and you get errors about your application not being allowed to link to it.

Does `find_package(OpenSSL 1.1 REQUIRED)` work?

**Comment by agouaillard-cosmo** [comment]
The way we set up our automated build, the path are passed through to the script. It allows to separate the cross-platform build, from platform and setting specific items. Here is an example for illustration purpose only.:

# computer specific names, paths, ....
include( site.cmake )

# libwertc revision
set( _rev 87 )

# Overwrite site.cmake
set( CTEST_BUILD_FLAGS     ""      )
set( CTEST_CMAKE_GENERATOR "Xcode" )

set( CTEST_BUILD_NAME "M${_rev}v23.2-MC-OSX-10.15-XCode-11.5-SDK10.14-Rel" )
set( CTEST_BUILD_CONFIGURATION Release      )

set( dashboard_model       Experimental     )
set( dashboard_git_branch  m${_rev}-v23.2 )
set( dashboard_source_name MC-${_rev}v23.2  )
# because of OBS hardcoded value, this must be an in source build.
set( dashboard_binary_name MC-${_rev}v23.2/Rel-build )
set( dashboard_do_coverage false            )

set( dashboard_git_url "git@github.com:CoSMoSoftware/OBS-studio-Webrtc.git" )

# DepsPath=/tmp/obsdeps
set( dashboard_cache "
  CEF_ROOT_DIR=${CEF_ROOT_DIR}
  ENABLE_SCRIPTING=OFF
  CMAKE_OSX_DEPLOYMENT_TARGET=10.14
  BUILD_BROWSER=true
  BROWSER_DEPLOY=ON
  OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl\@1.1/1.1.1g/
  OBS_VERSION_OVERRIDE=23.2.${_rev}
  libwebrtc_DIR=/Users/agouaillard/Dashboards/libwebrtc-${_rev}-Rel-H264-build/install_dir/cmake
  QTDIR=/usr/local/Cellar/qt/5.14.2
  Qt5_DIR=/usr/local/Cellar/qt/5.14.2/lib/cmake/Qt5
  ")

include( ../libwebrtc_common.cmake )
