### ISSUE TITLE
Functionality?

### ISSUE THREAD

**Issue by rayj00** [CoSMoSoftware/OBS-studio-webrtc#25]
Can the author or anyone else please describe the functionality of OBS-studio-webrtc?  How to actually use this and what are the capabilities?

**Comment by agouaillard-cosmo** [comment]
1 - this is a fork of OBS-Studio, and all functionality of OBS studio describe in the official site are preserved. Please refer to https://github.com/obsproject/obs-studio for original code and documentation.

2 - "This is a fork of OBS-studio with support for webrtc in general, and Janus Video Room plugin in particular." You can find more information about Meetech's Janus, and the video Room plugin there:
https://janus.conf.meetecho.com/videoroomtest.html

3 - The "Usage" Section of the readme should contain enough detail for you to connect to a janus server. Most notably, when choosing a webrtc target in the list of available streaming services (like janus, spankchain, ....), all the bandwidth settings are done automatically, as explained in #23 .

**Comment by agouaillard-cosmo** [comment]
@rayj00 does that answer your question? Can we close this ticket?

**Comment by rayj00** [comment]
Yes you can close this.

**Comment by agouaillard-cosmo** [comment]
thanks.
