### ISSUE TITLE
RF: October 19 crash reports

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#250]
Consistent crashes across several Macs using the RF build.

[2020-10-18 19-55-37.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5528019/2020-10-18.19-55-37.txt)
[2020-10-18 20-03-08.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5528021/2020-10-18.20-03-08.txt)

**Comment by matthewclickbid** [comment]
Is this why a mac installer wasn't included in the most recent RC?

**Comment by agouaillard-cosmo** [comment]
No. Mac builds now requires several extra steps (signing the app, notarising the app, notarising the dmg, stapling it), so it takes a few more days to be available. RC 3 on mac should be available tomorrow.

**Comment by matthewclickbid** [comment]
Thank you!

**Comment by matthewclickbid** [comment]
Downloaded latest Mac installer and when trying to start broadcast it errors with an Nvidia error. Wasnt there with previous version.

**Comment by alex-hijack** [comment]
I believe this is the same issue as #238. Testing to see if it happens again if File > Always On Top is selected in app.

**Comment by alex-hijack** [comment]
It just crashed again on OS 10.15.7. Looks like the same as #238

Thread 1 Crashed:
0   com.apple.iokit.IOHIDLib      	0x00000000105ba6ed 0x105ad000 + 55021
1   com.apple.iokit.IOHIDLib      	0x00000000105bb267 0x105ad000 + 57959
2   com.apple.framework.IOKit     	0x00007fff302e37ed IOHIDDeviceGetValue + 33
3   libobs.0.dylib                	0x000000010ed608bd obs_hotkeys_platform_is_pressed + 205
4   libobs.0.dylib                	0x000000010ed7a4d0 ops_hotkey_thread + 224
5   libsystem_pthread.dylib       	0x00007fff677a9109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff677a4b8b thread_start + 15

See OBS log and OS X report attached. It doesn't seem to happen when just streaming, it is when stopping a stream or using another app or in this case not starting a stream.

[2020-11-25 01-05-45.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5593757/2020-11-25.01-05-45.txt)

[OS X crash report.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5593758/OS.X.crash.report.txt)

**Comment by agouaillard-cosmo** [comment]
do you press any of the hotkey before that happens?
