### ISSUE TITLE
Remove dropped frames stats on webrtc

### ISSUE THREAD

**Issue by murillo128** [CoSMoSoftware/OBS-studio-webrtc#258]
Currently the dropped frames count is increased with the PLI/FIR stats when doing webrtc broadcasting, that causes a lot of confusion on users as they think it is a network problem.

**Comment by agouaillard-cosmo** [comment]
@ludocosmo I though we removed or renamed that?
I think it's better to just remove it. There is no way to present this stat in an understandable way for people not expert with RTP/RTCP

**Comment by agouaillard-cosmo** [comment]
see #232

**Comment by agouaillard-cosmo** [comment]
@ludo, can you remove the display part of this?

**Comment by agouaillard-cosmo** [comment]
Done in v26
