### ISSUE TITLE
macOS builds?

### ISSUE THREAD

**Issue by DatanoiseTV** [CoSMoSoftware/OBS-studio-webrtc#261]
Is there a macOS build?

**Comment by ryanmillicast** [comment]
You can browse to: https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases
Go To OBS-Studio 23.2 Webrtc m84 - RC 3
Click on "Assets"
Click on obs-webrtc-macOS-10.15-23.2.84.2.dmg to download Mac build
Here is the direct URL: https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/download/2.11/obs-webrtc-macOS-10.15-23.2.84.2.dmg

**Comment by cameronelliott** [comment]
One more question, I would like to be able to reproduce the builds, but the directions in this repo link to the original repo,
which says to use: ./CI/full-build-macos.sh
But that file is missing for this repo
Could you explain how to build this for macOS?

**Comment by agouaillard** [comment]
As indicated in the readme ad release version, this code is based on v23.2 of OBS-project.

You can find the corresponding tag listed there:
https://github.com/obsproject/obs-studio/tags?after=24.0.1

More specifically the commit for 23.2.0:
https://github.com/obsproject/obs-studio/tree/0d4d7f617c3f9a51ae04057ab78c4c7e4c78034b

At which point, you can look at the original builds files for indication (the travis, appveyor or azure YAML fils, respectively).

**Comment by proth1** [comment]
When do you expect that you might have a MacOS version with this newer version of OBS 26.1?

**Comment by agouaillard-cosmo** [comment]
OBS m84v26 is already available in the release section. The corresponding code is in the corresponding branch. Go ahead, download them and open as many ticket as you can ;-)

as for 26.1 it is planned but not schedule. here is the sequence of things that we have planned:
1 - finish porting the automated builds and packagers/installers
2 - finish porting the special builds (pac post and remote filming) inside the automated build framework
3 - add the NDI and web socket plugins to the builds
4 - open source and add all our integration tests.
5 - upgrade to m88 or m89
6 - upgrade to v26.1 or v27 if available then.

1 and 2 have started and are almost done.
4 has just started and can be done in parallel with 3.
5 will happen before 6, in sequence.

Next week I will open new tindividual tickets for those milestones, so people can follow them independently, and effort will be reported therein.

**Comment by proth1** [comment]
@agouaillard, thank you.  I am going to give it a bash.  I'm a newbie but will do the best I can.  I got the older version of OBS with the WebRTC to Millicast going last night and it was very impressive!!

![image](https://user-images.githubusercontent.com/20020726/103175226-5ff11100-4836-11eb-9daa-b986e2b51d79.png)

Thank you very much!!

**Comment by proth1** [comment]
@agouaillard I think I am confused.  When I try to find the installable MacOS dmg I keep ending back up at what appears to be the 23.2.84 release I already have installed, "OBS-Studio 23.2 Webrtc m84 - RC 3".  I went to the M84v26 Branch and it has a link back to [here](https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases).  I am doing something wrong or just misunderstanding that in fact 23.2.84 is the latest tagged release with support for MacOS?  That is certainly fine if that is the answer but just want to make sure I am just not misunderstanding.   Thanks!

**Comment by agouaillard-cosmo** [comment]
No, you are right, I have not finished the Mac installer because of all the notarisations and signing hoops I have to go through since Catalina. Plus I have a big Surprise build, and an M1 build ongoing .... Give me a couple of days. Sorry for the confusion.

**Comment by proth1** [comment]
No problem at all.  Thanks, Dr. Alex!!

**Comment by clickbid** [comment]
@agouaillard was looking to see if scripts will be available in the OSX update? Do you know when the OSX build will be available?

**Comment by agouaillard-cosmo** [comment]
We have just finished the build with NDI and web socket plugin for windows (today), and are currently doing the same for mac. I thought I would directly jump to that build, instead of doing intermediate release. Bear with us just a little bit longer.

**Comment by agouaillard-cosmo** [comment]
Alpha 2 has NDI and SDI.
Mac code signing and notarization is on the way for CI/CD. ETA january 15

**Comment by agouaillard-cosmo** [comment]
Alpha 2 for Mac available.
Beta for Mac should be available early next week.

**Comment by agouaillard-cosmo** [comment]
Beta 1 available, with also an upgrade of libwebrtc.

https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.16
