### ISSUE TITLE
Web browser support for v26 and ETA

### ISSUE THREAD

**Issue by clickbid** [CoSMoSoftware/OBS-studio-webrtc#264]
Will v26 support browsers as a source? I recall that being an issue with v23. Also, is v26 was still planned for a Christmas release.

**Comment by agouaillard-cosmo** [comment]
m84v26 status can be followed in ticket #244 that I just updated.

m84v26 will support browser source just as OBS v26 does, i.e. support it on mac and windows, but no support under linux.

**Comment by clickbid** [comment]
Thank you
