### ISSUE TITLE
Windows raise a pop-up for security

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#275]
prevent installation by default, require extra step.
Investigate.
alpha 2

**Comment by agouaillard-cosmo** [comment]
Depends on #272 .
Please write a KITE test for it BEFORE you remove the feature.

**Comment by agouaillard-cosmo** [comment]
it does not happen with vanilla OBS< so we must be forgetting some kind of windows signature.

**Comment by ludocosmo** [comment]
It seems some delay is needed for the pop-up security window not to be displayed anymore.
I tried installing the signed OBS installer on a Windows not used for development: Pop-up security window was displayed.
Two days later, I uninstalled OBS, then I tried to install it again: pop-up security window was not displayed.

**Comment by agouaillard-cosmo** [comment]
Do you know where the delay comes from? Is it server side (the registration of our certificate or our app at Microsoft?)
Is it on the OS (time to fetch certificate confirmation from somewhere)?

**Comment by ludocosmo** [comment]
It seems to be a combination of the code signing certificate reputation and the reputation of the CA that issued the certificate. The delay seems to be originating from server side (Microsoft).

> Application reputation is a method employed by Microsoft’s SmartScreen® filter to distinguish good software from bad software as it is downloaded from the Internet.

> SmartScreen’s Application Reputation engine looks at whether software has been blacklisted or whitelisted. It evaluates whether the software has been previously encountered by checking a large database of code that has been encountered and collected from telemetry capabilities that users have enabled on Windows machines.

> a warning appears if the software has been signed with a regular code signing certificate where the author or publisher has not yet established a reputation of trust. (Only Authenticode Certificates issued by a CA that is a member of the Windows Root Certificate Program can establish reputation.) As the software or its publisher gains a better reputation, the likelihood of a warning diminishes. Reputation for unsigned software is based on fingerprints while reputation based on signed software is based on the associated code signing certificate and the reputation of the CA that issued the code signing certificate.

Source: [https://www.digicert.com/dc/blog/ms-smartscreen-application-reputation/](https://www.digicert.com/dc/blog/ms-smartscreen-application-reputation/)

**Comment by ludocosmo** [comment]
List of Participants in Microsoft Trusted Root Program (Comodo is in the list).
[https://docs.microsoft.com/en-us/security/trusted-root/participants-list](https://docs.microsoft.com/en-us/security/trusted-root/participants-list)

**Comment by agouaillard-cosmo** [comment]
DONE.
