### ISSUE TITLE
obs-ndi - NewTek NDI™ integration plugin

### ISSUE THREAD

**Issue by colinbouvry** [CoSMoSoftware/OBS-studio-webrtc#279]
Hello,
I would like to integrate the plugin obs-ndi - NewTek NDI™ integration.
Is it possible ?
Thanks a lot

**Comment by agouaillard-cosmo** [comment]
Bonjour colin.

La version aligned sur OBS v26 a le support de NDI. Tu peux récupérer la version alpha 2 dans la partie release de ce projet par example. La version définitive devrait rapidement être disponible.

Si comme nous l espérons tu utilises millicast comme plateforme de distribution, tu peux aussi utiliser le millicast studio, qui est pour le moment plus simple que OBS Studio, mais qui supporte NDI nativement sans plugin:
https://github.com/CoSMoSoftware/MillicastNative-Public

**Comment by colinbouvry** [comment]
Merci beaucoup.
La version alpha 2 OBS v26 fonctionne avec millicast et NDI.
Le problème est la watermark.
La version définitive (production) devrait arriver quand ?
Millicast studio plante avec NDI en entrée.
Bravo pour cette version OBS-studio-webrtc, c'est prométeur et je suis convaincu de son utilité.

**Comment by agouaillard-cosmo** [comment]
Bonjour,

La watermark est la pour différencier de façon indéniable les versions alpha (support limite) des versions production (support complet). Il y a eu beaucoup d abus dans le passe. Dans une ou deux semaines quand la version commerciale sera disponible il n y aura pas de watermark.

Millicast studio devrait marcher avec NDI. Si ca plante, n'hésitez pas a ouvrir un ticket dans le repertoire correspondent, en détaillant bien le system opératoire utilise, la version utilise et la source NDI utilisée.

**Comment by agouaillard-cosmo** [comment]
m84 et m86 Beta 1 n'ont plus de waterark et on le plugin NDI.

https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.16
