### ISSUE TITLE
Intermittently out of sync 

### ISSUE THREAD

**Issue by kimilpyoung** [CoSMoSoftware/OBS-studio-webrtc#281]
Hi
I used webrtc-obs ver 23 
When broadcasting on OBS, audio and video are intermittently out of sync.
Usually there is a difference of about 0.5 seconds.

Is it possible to check if it is a network effect or a obs configuration problem?
I am using janus through whip protocol

**Comment by agouaillard-cosmo** [comment]
Hi kimil.

Sorry, neither cosmo nor meteecho have the cycle to provide support on OBS/whip/janus at this time. It is likely that it will remain that way for some time.

The beauty of open-source is that, it does not block you from fixing the problem yourself.

Patches are welcome.
