### ISSUE TITLE
26.0.2 Custom WebRTC Streaming Platform / show message

### ISSUE THREAD

**Issue by kimilpyoung** [CoSMoSoftware/OBS-studio-webrtc#288]
I try to use this function now, a message appears
"Your service settings are not complete. Open the settings => stream window and complete them."

I know this menu use whip
Is that version not available?
Is there anything I can contribute?

**Comment by agouaillard-cosmo** [comment]
For now, this options is not available anymore.
We are planning t bring it back in sometimes after CNY.
Please follow #289 for updates on availability of Custom WebRTC Servers again.
