### ISSUE TITLE
KITE can't interact with multiple elements on mac

### ISSUE THREAD

**Issue by A-nguyenv** [CoSMoSoftware/OBS-studio-webrtc#289]
Some elements are not interactable with KITE on mac:
- [x] Start streaming and start recording buttons
- [x] All tabs in Settings: General/Stream/Output/Audio/Video/Hotkeys/Advanced
- [x] Service list items in Stream tab
  - [x] millicast (WebRTC/WS) only
  - [ ] add millicast (RTMP)
  - [ ] add custom WebRTC (WHIP)
- [x] Codec list items in Stream tab

**Comment by ludocosmo** [comment]
On OBS v23 the list of services was replaced by a single service: "MIllicast,", therefore it was not editable.
For OBS v26:
- shall we keep the list of services and transform the combo box into a list of radio buttons?
- or shall we keep only a single service "Millicast" not editable?

**Comment by agouaillard-cosmo** [comment]
three phases:
- millicast (WebRTC/WS) only
- add millicast (RTMP)
- add custom WebRTC (WHIP)

For discussion at the daily tomorrow.

**Comment by ludocosmo** [comment]
ComboBox for list of services has been replaced by a list of radio buttons with only one radio button for now:

- Millicast WebRTC
