### ISSUE TITLE
Add macOSX binary to releases

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#29]

**Comment by cosmo-rn** [comment]
The macOS binary is available in the releases.

**Comment by ruddell** [comment]
The macOS binary has some incorrect links to libraries in the compiled version and will crash before startup.  For example, it expects the end-user to have QT5 and ffmpeg installed locally:

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Volumes/VOLUME/*/OBS.app/Contents/Resources/bin/obs
  Reason: image not found
```
```
Dyld Error Message:
  Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib
  Referenced from: /Volumes/VOLUME/*/OBS.app/Contents/Resources/bin/obs
  Reason: image not found
```
([full error log for ffmpeg](https://pastebin.com/raw/ziQiP5z9))

**Comment by agouaillard-cosmo** [comment]
@ruddell this is a different issue, and current ticket is closed. Next time, please open a new ticket. This time i went ahead and did it for you. Please see #34

**Comment by ruddell** [comment]
Sorry about that and thanks for being so responsive.  My thinking was that this ticket shouldn't have been closed if the binary is invalid, in the future I'll open separate issues for each problem.

**Comment by agouaillard-cosmo** [comment]
there was no macOS binaries in the previous release, hence this ticket. I
understand the title was confusing :-) thanks for the feedback.
