### ISSUE TITLE
Implement auto-reconnect when websocket is disconnected

### ISSUE THREAD

**Issue by murillo128** [CoSMoSoftware/OBS-studio-webrtc#291]
Currently if websocket connection is disconnected abruptly, OBS stops streaming. We should implement an auto-reconnect feature which automatically tries to reconnect to the server and restart the streaming as it is currently done with rtmp.

**Comment by SCG82** [comment]
Since the websocket connection is only used one time after broadcasting begins—for sending the disconnect message—what about disconnecting once signaling is complete and reconnecting at the end of broadcasting to send the disconnect message?

**Comment by agouaillard-cosmo** [comment]
We use the web socket underlying transport as a keep alive information on the server side.
If the websocet connection goes down, the server disconnects the stream.

**Comment by ludocosmo** [comment]
Behaviour is different for each OS.

Mac
- Start streaming, green square displayed on status bar, bitrate about 2300 kb/s, streaming button is labeled "Stop Streaming", streamed video visible on Millicast viewer
- Shutdown internet connection
- Square remains green and bitrate still about 2300 kb/s, but Millicast viewer displays a still image (the last one received before internet shutdown)
- After about 15 seconds, OBS stops streaming (green square and bitrate disappear from status bar, and streaming button is labeled "Stat Streaming"), and one or two identical information window(s) is/are displayed saying "An unexpected error occurred when trying to connect to the server. More information in the log file. Connection failure"
- Click OK on information window
- Resume internet connection
- Click button "Start Streaming" ==> 2 possibilities
   + either OBS crashes
   + or an information window is displayed with the message "An unexpected error occurred when trying to connect to the server. More information in the log file." But streaming starts anyway, grren sqaure and bitrate in hte status bar, streaming button is labeled "Stop Streaming", and Millicast viewer displays the streamed video.

**Comment by agouaillard-cosmo** [comment]
blocked by #311

**Comment by ludocosmo** [comment]
Done by Sergio
