### ISSUE TITLE
Close must be carried out on a separate thread in order to avoid deadlock

### ISSUE THREAD

**Issue by SCG82** [CoSMoSoftware/OBS-studio-webrtc#298]
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L160
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L233
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L265
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L287
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L358
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L379
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L442
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L457
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L588
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L644
* https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/907cc71e6f318661f4a75b026a6b7d0318036f53/plugins/obs-outputs/WebRTCStream.cpp#L653

**Comment by agouaillard-cosmo** [comment]
done
