### ISSUE TITLE
Crashes when opening settings

### ISSUE THREAD

**Issue by setstream** [CoSMoSoftware/OBS-studio-webrtc#308]
Every time I try to open the settings the app crashes.
Running 26.1.2 m88 Beta 1 (2.18 - 907cc71)  on a trash can Mac (3.5Ghz 6 core Xeon e5, 32Gb ram, os 10.14.5 Mojave).  I received a report today that this happens on windows too with the following setup: Windows 10 Pro (19042), custom Workstation with a Ryzen 3950x, Nvidia RTX 3090, ASRock X570 Creator Motherboard and 64gb 2666 mhz corsair ram.
Settings work correctly on a new M1 Macbook Pro running OS 11.2.1 (Big Sur)

Steps to reproduce:
Open OBS-WebRTC 
Click "Settings"

Crash Report attached

[OBS_WebRTC-CrashReport.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/6087213/OBS_WebRTC-CrashReport.txt)

**Comment by agouaillard-cosmo** [comment]
OBS is not designed to have several installations on the same machine, and even if you delete the application folder, it leaves a persistent data folder behind, which can cause a lot of problem.

on windows the folder is (WinKey+R):
%appdata&\obs

on Mac:
~/Library/Application Support/obs-studio/

on Linux:
~/. config/obs-studio

can you just (back up, set aside) delete the folder and try again?

**Comment by setstream** [comment]
> OBS is not designed to have several installations on the same machine, and even if you delete the application folder, it leaves a persistent data folder behind, which can cause a lot of problem.
> 
> on windows the folder is (WinKey+R):
> %appdata&\obs
> 
> on Mac:
> ~/Library/Application Support/obs-studio/
> 
> on Linux:
> ~/. config/obs-studio
> 
> can you just (back up, set aside) delete the folder and try again?

You're absolutely right.  It was a stored settings issue on my mac.  I'll remember to delete the settings folder every time I change versions.
Thanks!
