### ISSUE TITLE
Wire OBS's Stats panel

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#310]
![](https://user-images.githubusercontent.com/11771024/108611829-76d45f80-73b0-11eb-96f2-5146609e2b56.png)

**Comment by ludocosmo** [comment]
Added some WebRTC stats.
![Screenshot 2021-03-24 at 16 16 34](https://user-images.githubusercontent.com/30816985/112277217-7b947800-8cbc-11eb-96ec-83cf3d42bdcd.png)

**Comment by agouaillard-cosmo** [comment]
DONE.
