### ISSUE TITLE
compile the websocketclient module inside obs-output

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#311]
avoid some startup path problems, and hopefully addresses the crash on mac and linux when web socket disconnect

**Comment by agouaillard-cosmo** [comment]
Building version has just been pushed in the m90-v26.1.2-Merge-WS-DLL. did not try to run it.
Windows behaviour might need to be changed, as I left it as a SHARED library.
CMake part should be compelte.
next: ludo to make a full release and test if it runs.

**Comment by agouaillard-cosmo** [comment]
- CMake integration (up to compilation) done and delivered.
- needs to use openssl build of libwebrtc
- validated that it can stream on Linux (Ludo)
being validated.

**Comment by ludocosmo** [comment]
- Using libwebrtc woth openssl enabled
- Streaming on linux/windows/mac OK
