### ISSUE TITLE
All streaming service options missing except for Millicast

### ISSUE THREAD

**Issue by czyz** [CoSMoSoftware/OBS-studio-webrtc#312]
I'm only seeing the option of streaming to either "Millicast-WebRTC" or "Millicast-RTMP". Is this by design? I had thought these builds would also allow streaming to janus gateways.

Thanks for any info.

OBS-WebRTC 26.1.2-m90 on macOS 10.13.6.
![Screen Shot 2021-03-22 at 4 37 30 PM](https://user-images.githubusercontent.com/345036/112071428-f6c72400-8b2c-11eb-94c1-ea8deb6a80ac.png)

**Comment by agouaillard-cosmo** [comment]
hi czyz.
The support for Janus is pending support for WHIP, and Janus then adding public WHIP support.
You can follow progress on that matter in ticket #301

**Comment by czyz** [comment]
Ah, that makes sense. Thanks.
