### ISSUE TITLE
add voice feedback to OBS

### ISSUE THREAD

**Issue by liubigbear** [CoSMoSoftware/OBS-studio-webrtc#313]
hello CoSMo

I'm trying to add voice feedback to OBS.  Capture and send  audio stream to obs server by following js code

            navigator.mediaDevices.getUserMedia({ audio: true, video: false })
            .then(function (stream) {
                _this.UserVoiceStream = stream;
                const tracks = _this.UserVoiceStream.getTracks();
                if (tracks.length > 0) {
                    _this.UserVoiceStream.getTracks().forEach(track => _this.rtcConnection.addTrack(track, _this.UserVoiceStream));
                    console.log("Added audio track to peerconnection");  } })

on OBS server side,  the peerconnection onAddTrack was called and I can get AudioTrack,   I add a sink to it ,but  AudioTrackSinkInterface::onData never called.   According to Webrtc log, I know audio packets arrived,  I just need to find a good way to get it.  This seems to be a webrtc issue.    I'm trying to find a solution to receive audio packets without disturbing OBS broadcasting.   do you have a plan to add voice feedback?  or have any idea on this.

BR
Mark

**Comment by liubigbear** [comment]
add a patch to webrtc, done!

**Comment by pccq2002** [comment]
> add a patch to webrtc, done!

how do you fix the issue with the patch？
