### ISSUE TITLE
Segregated data folders

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#317]
to avoid crash with conflicting versions, either between OBS and OBS-Webrtc or between OBS-webrtc versions themselves, segregate the data folder with a version unique name.

The name of the data folder is dealt with in cmake if I remember correctly.

**Comment by setstream** [comment]
+1 Adding my support for this feature.  Thanks

**Comment by agouaillard-cosmo** [comment]
Implemented for the Remote Filming build.
There is one remaining write to the wrong folder for the main build, to be verified.
Should be done in time for SongKran Release, so adding it to the corresponding milestone.

**Comment by ludocosmo** [comment]
Done
