### ISSUE TITLE
Can I customize the push address?

### ISSUE THREAD

**Issue by Rendtime** [CoSMoSoftware/OBS-studio-webrtc#326]
Must be the service of millicast?  Can I customize the push address?

**Comment by llspalex** [comment]
I would like to know this too - the [latest release](https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.21) lists only Millicast WebRTC and Millicast RTMP. 

[23.2.84](https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.11) lists "Custom WebRTC Streaming Platform" which I believe uses WHIP. 

Would it be possible to reinclude "Custom WebRTC Streaming Platform" in the next release @ludocosmo?

**Comment by lizardpeter** [comment]
I am wondering the same thing. I have issues with older builds but cannot update to these since they don't support Janus.

**Comment by murillo128** [comment]
Due to the efforts required to support multiple platforms, currently only publishing to mllicast platform is supported.
