### ISSUE TITLE
Ubuntu 20.10 obs-webrtc-x64-26.1.2-m90.deb doesnt install missing required dependency

### ISSUE THREAD

**Issue by drfrog666** [CoSMoSoftware/OBS-studio-webrtc#327]
obs-webrtc deb requires libfdk-aac1 but only libfdk-aac2 exists on ubuntu 20.10

**Comment by ludocosmo** [comment]
Dependencies updated for Ubuntu 20.10
[https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/download/2.21/obs-webrtc-x64-26.1.2-m90-2.21-u20.10.deb](https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/download/2.21/obs-webrtc-x64-26.1.2-m90-2.21-u20.10.deb)

**Comment by drfrog666** [comment]
Installed without issue
