### ISSUE TITLE
Could NOT find LibWebRTC (missing: WEBRTC_LIB)

### ISSUE THREAD

**Issue by anh2111htdd** [CoSMoSoftware/OBS-studio-webrtc#329]
Hi, I am building `OBS-studio-webrtc` with the instruction from https://github.com/obsproject/obs-studio/wiki/Install-Instructions and am stuck at ` cmake-gui` Configure step: 

![image](https://user-images.githubusercontent.com/76768126/120856334-45278300-c5b2-11eb-9141-0fc30c3a8702.png)

Would appreciate any suggestion to proceed further! I have tried the followings:
- Set `WEBRTC_LIB` to the path of a built libwebrtc cloned from https://github.com/aisouard/libwebrtc
- Built `obs-studio` to verify my environment. The build was successful without `webrtc`.
- Run `install-dependencies-win.cmd` and `install-script-win.cmd` but I didn't see they download any files related to `webrtc `
- Checked closed issues on this. I found a related issue: https://github.com/CoSMoSoftware/OBS-studio-webrtc/issues/46 but the links provided are now 404, so I couldn't see the solution.

Thanks in advance!

**Comment by ZZhang430** [comment]
I think Cosmo own them. Not free.

**Comment by cameronelliott** [comment]
@ludocosmo Is that correct, that the WEBRTC_LIB needed is closed-source, and not available except to paid licensees? Or is the WEBRTC_LIB used in the release builds open-source and freely available?
If the WEBRTC_LIB used in the release builds of this fork, is the URL for it, `https://github.com/aisouard/libwebrtc` or something else? 
It would be great to know if the comment by @ZZhang430 is true or not, and whether I can rebuild the releases binaries with open-source or I would need a license from Cosmo.
Thanks

**Comment by ludocosmo** [comment]
@cameronelliott Yes it's correct that the libwebrtc we use is closed source. It is basically the same libwebrtc as the one you can get from `https://webrtc.org/` with the addition of few patches to avoid incompatibilities with TLS and SSL used by OBS.
We build our own version of libwebrtc, which is different from `https://github.com/aisouard/libwebrtc`
We provide our compiled libwebrtc for paid licensees.

**Comment by anh2111htdd** [comment]
Got it, thanks all for the replies.

**Comment by qq88797833** [comment]
There has been a libwebrtc.lib  ，but cmake.gui  How to set up
