### ISSUE TITLE
Debian packages don't run on Debian

### ISSUE THREAD

**Issue by jech** [CoSMoSoftware/OBS-studio-webrtc#334]
```
$ obs
obs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/libobs.so.0)
```
Right now, Debian testing has libs 2.31 and Debian unstable has 2.32.

Please recompile against a less recent version of libc.

**Comment by ludocosmo** [comment]
Added package obs-webrtc-x64-27.1.3-m95-2.24-debian11.deb for Debian 11.
See release tagged 2.24
https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.24
