### ISSUE TITLE
Stream Deck

### ISSUE THREAD

**Issue by turokevie** [CoSMoSoftware/OBS-studio-webrtc#335]
It seems the Stream Deck does not work with this I added the plugin manually and the steam deck does not see obs.

**Comment by wdlev** [comment]
Fixes for this below. Courtesy of @ludocosmo. Important: before you install Stream Deck software, make sure you have regular OBS installed.

MAC
1) Regular OBS needs to be installed on your Mac
2) Install Elgato software on your Mac
3) Open a Finder window.
4) Open menu Go --> Go to Folder...
5) Put the following folder path:
/Library/Application Support
6) You should see the contents of folder /Library/Application Support & a folder named "obs-studio"- make a copy (duplicate) of that folder "obs-studio" (you will be asked for your password to complete that action)
7) The new folder is named "obs-studio copy"
- Rename it as "obs-webrtc" (you will again be asked for your password)
8) Launch OBS-WebRTC.
9) Go to Tools on the menu bar and hopefully you see Elgato plugin in the menu tools... click on it. It should simply give you info on the plugin.
10) Launch StreamDeck... you should be good now!

PC
1) Regular OBS needs to be installed on your Mac
2) Install Elgato software on your Mac
3) Go to C:\Program Files\obs-studio\obs-plugins\64bit
4) Copy the following two files: StreamDeckPlugin.dll and StreamDeckPlugin1.dll
5) Paste them in: C:\Program Files\OBS WebRTC (64bit)\obs-plugins\64bit
6) Launch OBS-WebRTC.
7) Go to Tools on the menu bar and hopefully you see Elgato plugin in the menu tools... click on it. It should simply give you info on the plugin.
8) Launch StreamDeck... you should be good now!
