### ISSUE TITLE
README does not say what this project accomplishes using WebRTC

### ISSUE THREAD

**Issue by david672orford** [CoSMoSoftware/OBS-studio-webrtc#339]
The readme says that this projects integrates an WebRTC implementation into OBS Studio. Having looked up Janus, WHIP, and Millicast and noting that the code is in a directory called "obs_outputs", I am pretty sure that this project makes it possible to stream the output of OBS Studio to a streaming platform using WebRTC. It probably does not enable one to pull video from a WebRTC video conference.

It would be helpful to add one or two sentences explaining what OBS-Studio with these patches can do with WebRTC streams.

**Comment by murillo128** [comment]
This project is now limited to publish to webrtc to Millicast platform only.
