### ISSUE TITLE
WHIP implementation

### ISSUE THREAD

**Issue by mango009** [CoSMoSoftware/OBS-studio-webrtc#341]
From this [article](https://millicast.medium.com/whip-the-magic-bullet-for-webrtc-media-ingest-57c2b98fb285), Millicast describes about `WHIP` and the quote

```
On the client side, Millicast created an OBS fork that has a complete implementation that makes it easy to evaluate the workflow
```

But I don't find WHIP implementation in this fork from reading the code. So the article is kind of misleading?

**Comment by murillo128** [comment]
The article was written in 2020, since then , we decided to remove the support of WHIP from our fork of OBS because it requires a lot of effort to maintain.  

We hope that WHIP is natively supported on the official OBS project soon which we will collaborate with as best as we can.

**Comment by SetoKaiba** [comment]
@murillo128 Does it mean this obs will only work with millicast now?

**Comment by murillo128** [comment]
yes
