### ISSUE TITLE
bulid webrtc dep 

### ISSUE THREAD

**Issue by qq88797833** [CoSMoSoftware/OBS-studio-webrtc#343]
![image](https://user-images.githubusercontent.com/28855943/178171414-702c19c0-32b7-45ff-b67c-99b0e86a3d15.png)

**Comment by ludocosmo** [comment]
We do not provide libwebrtc dependency.
The libwebrtc we use is closed source. It is basically the same libwebrtc as the one you can get from https://webrtc.org/ with the addition of few patches to avoid incompatibilities with TLS and SSL used by OBS.
