### ISSUE TITLE
Issues when installing in a non-default directory

### ISSUE THREAD

**Issue by gbraad** [CoSMoSoftware/OBS-studio-webrtc#35]
The shortcut link points to obs64.exe, but it can not be found... and when browsed to the location, it can not start as it can not located the locale file

![image](https://user-images.githubusercontent.com/1894/42797711-fbacdba4-89c2-11e8-8d85-4f54064e6962.png)

![image](https://user-images.githubusercontent.com/1894/42797726-1e6c651a-89c3-11e8-8c43-b1c3feaa83b7.png)

When startimg directly from `obs64.exe` in the installed directory, `C:\Program Files\OBS Studio WebRTC (64bit)\bin\64bit` in my case. it works... So the start directory is likely wrongly defined in the shortcut.

**Comment by agouaillard-cosmo** [comment]
Hi @gbraad, thanks for the feedback.
Just to be sure how to reproduce your problem, can you specify the link or location of the installer you try to use, and wether you kept the default options or change anything?

**Comment by gbraad** [comment]
As mentioned; I installed using non-default location; I added WebRTC in the
path name.

**Comment by agouaillard-cosmo** [comment]
Can you specify the link or the location where you downloaded the **installer** you used?

**Comment by gbraad** [comment]
From your releases, tagged 2.1

https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.1

**Comment by agouaillard-cosmo** [comment]
Thanks, we will go ahead and investigate.

**Comment by agouaillard-cosmo** [comment]
Ben, please validate it is still a problem with the new packages.

**Comment by Ben-cos** [comment]
Can't reproduce this issue with the latest installer on Windows. (successfully installed OBS-webrtc in a non-default directory).
