### ISSUE TITLE
Crashing on every "Start Stream"

### ISSUE THREAD

**Issue by YuMing-King** [CoSMoSoftware/OBS-studio-webrtc#363]
..........
(audio_processing_impl.cc:275): Denormal disabler: supported
info: (audio_processing_impl.cc:275): Denormal disabler: supported

(webrtc_voice_engine.cc:321): WebRtcVoiceEngine::WebRtcVoiceEngine
info: (webrtc_voice_engine.cc:321): WebRtcVoiceEngine::WebRtcVoiceEngine

(webrtc_video_engine.cc:619): WebRtcVideoEngine::WebRtcVideoEngine()
info: (webrtc_video_engine.cc:619): WebRtcVideoEngine::WebRtcVideoEngine()

(webrtc_voice_engine.cc:343): WebRtcVoiceEngine::Init
info: (webrtc_voice_engine.cc:343): WebRtcVoiceEngine::Init

obs: symbol lookup error: /usr//lib/obs-plugins/obs-outputs.so: undefined symbol: fcntl64

obs-webrtc-x64-1.3.2-27.2.4-m100-1804.deb     Ubuntu 18.04.6 LTS

**Comment by ludocosmo** [comment]
Please upgrade to latest version which solves the problem.
