### ISSUE TITLE
I want install Advanced Scene Switcher in UBUNTU 

### ISSUE THREAD

**Issue by GITSALAHE** [CoSMoSoftware/OBS-studio-webrtc#367]
Hi I am customer at DOLBY.IO 
I had problem how I can install https://obsproject.com/forum/resources/advanced-scene-switcher.395/ in your [OBS-studio-webrtc] ?
I need it too much 
Thank you

**Comment by ludocosmo** [comment]
OBS-webrtc use different install folder than regular OBS-sutdio, so you have to put by yourself the advanced-scene-switcher plugin files in the correct folders as follows.
I will describe how to install the latest release of advanced-scene-switcher plugin:
[https://github.com/WarmUpTill/SceneSwitcher/releases/tag/1.20.5](url)

- Get the ZIP file advanced-scene-switcher-linux-x86_64.zip
- Move file advanced-scene-switcher-linux-x86_64.zip into an empty folder
- cd to that folder
- unzip advanced-scene-switcher-linux-x86_64.zip 

**Copy plugin binaries into /usr/local/lib/obs-plugins**
cd obs-plugins/64bit
sudo cp -R * /usr/local/lib/obs-plugins
cd ../..

**Copy locale and resource files into /usr/local/share/obs/obs-plugins**
cd data/obs-plugins
sudo cp -R advanced-scene-switcher /usr/local/share/obs/obs-plugins
cd

You may launch OBS-webrtc. 
Advanced Scene Switcher should be accessible from the Tools menu.
