### ISSUE TITLE
Fix libwebrtc version number to avoid mismatch

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#38]
find_package( libwebrtc 65 REQUIRED ) should work, but I can't test here.

**Comment by david-bui** [comment]
Test procedure :

Replace to **find_package( libwebrtc 65 REQUIRED )**
Install libwebrtc M60, configure OBS
**Expected :** 
An error issued by CMake
**Result :** 
An error was issued.

Test was also done when libwebrtc M65 was installed, and it **worked**
