### ISSUE TITLE
add a token input UI for millicast

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#52]
inspiration can be taken from spakchain UI.

**Comment by Ben-cos** [comment]
Done on 82286452e75e16a3ffa0bdc084dbb339d70306df, I will close the ticket once the release is ready.

**Comment by Ben-cos** [comment]
Done on release 2.6

**Comment by agouaillard-cosmo** [comment]
you should not copy the hash of the commit in comments, you should put the number of the bug in the commit message for auto insertion in the feed:

"WIP: bla bla bla #52"
