### ISSUE TITLE
OBS not streaming h264 on Windows 10

### ISSUE THREAD

**Issue by wesleystrikes** [CoSMoSoftware/OBS-studio-webrtc#54]
- Environment:

Microsoft Windows 10 home edition
OBS version 2.5-2 gf32b29ae

- Steps to reproduce:

1. Go to millicast.com page
2. Download and install latest widows OBS version 2.5-2 gf32b29ae
3. Tested with millicast account, publishing Websocket URL: wss://live.millicast.com:443/ws/v1/pub?token=6022f960abce03b5895c2dbb8d8a06d9608d6e37a7c3e00f4ddd42ca8f1451ce
Publishing stream name: roberts
Video Codec: tried h264 and H264

- Expectation: start streaming

- What happens: OBS Start Streaming button locks up. OBS does not publish. In order to stream you need to exit OBS and restart. Streaming starts after removing h264 from video codec field, however the steam is not viewable on Safari.

- OBS log attached

- Questions for devs:

When the video codec field is left empty, does it default to vp8?
[obs logs.zip](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/2493755/obs.logs.zip)

**Comment by agouaillard-cosmo** [comment]
David,

Can you please:
open a new ticket for the start/stop streaming,
Reference that ticket here,
Then close this ticket.

**Comment by david-bui** [comment]
Button locked up issue : #55
