### ISSUE TITLE
Can we get a WebRTC Source?

### ISSUE THREAD

**Issue by WACOMalt** [CoSMoSoftware/OBS-studio-webrtc#58]
The browser source is limited in that you cant control audio for it. I only need webRTC for my input media but will final the stream to Mixer.com. I'm hoping to only use WebRTC to minimize delay prior to the final stream.

**Comment by agouaillard-cosmo** [comment]
You can find the source of libwebrtc there:
https://chromium.googlesource.com/external/webrtc/
