### ISSUE TITLE
Obs  Url

### ISSUE THREAD

**Issue by a0412comwg** [CoSMoSoftware/OBS-studio-webrtc#60]
![image](https://user-images.githubusercontent.com/21072395/48239830-61b7aa80-e40b-11e8-91e7-f37769808ef7.png)
Is the URL in the correct format?
when i start obs    ,obs  crashed

**Comment by Ben-cos** [comment]
There is an issue using Janus with the current version, I will push a fix soon.

**Comment by debianking** [comment]
I have the same problem.
- The stream type set to WebRTC Janus Streaming Server.
- The Web Server Name set to ws://myserver ip:8188
- The Server Room set to 1234(janus defaut configuration)

when i start the obs to push stream , the obs crashed and exited.
I'm not sure if URL set up a mistake or something else.
Does Web Server Name mean URL? How do I give the correct URL or name?

**Comment by agouaillard-cosmo** [comment]
You are correct, there is an error on our side. We are preparing a fix, and
will make it available soon.

**Comment by debianking** [comment]
Have you solved the problem?
expect the release of the new version.

**Comment by Ben-cos** [comment]
Fixed in last release (tag 2.7). Note: For now, we only support connection through WebSocket secure (wss), you can get more details inside the README.
