### ISSUE TITLE
C# wrapper for OBS-studio-webrtc

### ISSUE THREAD

**Issue by Raj123456788** [CoSMoSoftware/OBS-studio-webrtc#61]
The only one I can find was [libobs-sharp](https://github.com/GoaLitiuM/libobs-sharp)
If anyone has tried OBS-studio-webrtc.

Suggestions Welcome. Thanks!

**Comment by agouaillard-cosmo** [comment]
Dear Raj,

- OBS-studio-webrtc is an application, there is no "wrapper" for application, only for libraries.

- if you are looking for a C# wrapper for libOBS, you need to ask in the OBS discord channel,
- if you are looking for a C# wrapper for libwebrtc, you need to ask in the discuss-webrtc mailing list.
in any case, we do not provide either.
