### ISSUE TITLE
"Undefined symbols for architecture x86_64" when building OBS on Mac OS X

### ISSUE THREAD

**Issue by klommenz** [CoSMoSoftware/OBS-studio-webrtc#65]
Hello everyone,

First of all, take you all for taking the time and making this project available. 

I have been trying to build the project for four days now, several hours at a time. I know, this is normal. After all, dark magic is involved here, and there are no shortcuts.

My build machine is OSX 10.14.2, with Xcode SDK versions 10.12 and 10.14.

Expectedly, I am running into issues, and could use your help with one question. I am also putting all the steps I have taken so far, with the intention of helping future non-webrtc experts who might run through the same difficulties I had.

1. I have cloned WebRTC 65, and built it in a Vanilla version. No special difficulties there.
2. lipo -info libwebrtc.a returns:

```
    Non-fat file: libwebrtc.a is architecture: x86_64
```

3. Next, I had to start modifying my cmake files. I started by pointing to the include files, libs and directories for webrtc, and some of the header files that were required in WebRTCStream.cpp

```
include_directories("${DEV_DIR}/webrtc-checkout/src")
include_directories("${DEV_DIR}/webrtc-checkout/src/third_party")
include_directories("${DEV_DIR}/webrtc-checkout/src/third_party/abseil-cpp")
include_directories("${DEV_DIR}/webrtc-checkout/src/third_party/libyuv/include")

set( obs-outputs_PLATFORM_DEPS
   ${DEV_DIR}webrtc-checkout/src/out/Default/obj/libwebrtc.a )
```

4. Next, I added two definitions, after getting errors of a flavor - "Platform not supported"

```
add_definitions(-DWEBRTC_MAC)
add_definitions(-DWEBRTC_POSIX)
```
4a. I did something with openSSL, but for the life of me, I don't remember what I did. I think something in the cmake of the websocket client directory.

5. Next, I started getting some errors that seemed like Mac OSX specific, and started to link frameworks:
```
    find_library(FOUNDATION_FRAMEWORK Foundation)
    find_library(AVFOUNDATION AVFoundation)
    find_library(SECURITY_FRAMEWORK Security)
    find_library(COCOA Cocoa)
    find_library(AUDIOUNIT AudioUnit)
    find_library(AUDIOTOOLBOX AudioToolbox)
    find_library(COREMEDIA CoreMedia)
    find_library(COREVIDEO CoreVideo)
    find_library(COREAUDIO CoreAudio)
    find_library(COCOA Cocoa)
    find_library(COREMEDIAIO CoreMediaIO)

    set( obs-outputs_PLATFORM_DEPS
      ${AVFOUNDATION}
      ${COCOA}
      ${COREFOUNDATION}
      ${AUDIOUNIT}
      ${AUDIOTOOLBOX}
      ${COREMEDIA}
      ${COREVIDEO}
      ${COREAUDIO}
      ${COREMEDIAIO}
      ${FOUNDATION_FRAMEWORK}
      ${SECURITY_FRAMEWORK}

      target_link_libraries( obs-outputs
       ${SSL_LIBRARIES}
       ${ZLIB_LIBRARIES}
       ${AVFOUNDATION}
       ${COCOA}
       ${COREFOUNDATION}
       ${AUDIOUNIT}
       ${AUDIOTOOLBOX}
       ${COREMEDIA}
       ${COREVIDEO}
       ${COREAUDIO}
       ${COREMEDIAIO}
       ${obs-outputs_PLATFORM_DEPS}
       libobs
       websocketclient
      )
```

Note: I went all in with all those libs, because i didn't know which ones were absolutely needed. Will clean it up, after I have the patience to run builds and see which ones break the build.

6. Now, I am officially stuck, and when i try to link obs-outputs, I get this error which I don't know how to get around:

```
[ 83%] Linking CXX shared module obs-outputs.so
Undefined symbols for architecture x86_64:
  "typeinfo for webrtc::videocapturemodule::VideoCaptureImpl", referenced from:
      typeinfo for rtc::RefCountedObject<webrtc::videocapturemodule::VideoCaptureImpl> in WebRTCStream.cpp.o
  "typeinfo for cricket::WebRtcVideoCapturer", referenced from:
      typeinfo for VideoCapturer in WebRTCStream.cpp.o
  "non-virtual thunk to cricket::WebRtcVideoCapturer::OnFrame(webrtc::VideoFrame const&)", referenced from:
      vtable for VideoCapturer in WebRTCStream.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/obs-outputs/obs-outputs.so] Error 1
make[1]: *** [plugins/obs-outputs/CMakeFiles/obs-outputs.dir/all] Error 2
make: *** [all] Error 2

```

I am quite dumbfounded by this one, and have no idea how to continue next. I have seen some postings around RTTI, which i tried to activate on cmake, to no avail. If anyone has a tip on where to go next with this, it would be great.

Thanks,
Eran

**Comment by agouaillard-cosmo** [comment]
Don't thanks us, thanks jim for all the good work and for choosing a GPL license. :-)

Note that all of those are libwebrtc questions and not obsolete questions ......

Good news and bad news:
- you re almost there, and you've past most of the difficult steps
- you will need to rollback some stuff, and what remains, while not being difficult, takes a  lot of time.

1. Use 69.

2. For a full openssl compatible libwebrtc build, you need to compile openssl yourself, and then use the patch we just provided to google [here](https://bugs.chromium.org/p/webrtc/issues/detail?id=10160) (that can take a very long time to figure out, even with all the code, good luck there). This is a patch against 69.

Note, we are planning to simplify this. I'm not convinced this is needed. It is in my todo list for Q1. This is **way** too painful. see and follow #63

3. when you see type info missing on a class you need to subclass (capturer, observer, callback), it s always an RTTI problem. You need to configure libwebrtc compilation to use RTTI:
"gn gen <all_my_usual_params> use_rtti=true"

**Comment by klommenz** [comment]
Alex,

Thank you for your comments. I have added the use_rtti, and it solved two of the three error messages I received (More on that ahead)

I have applied the patches, and did run into some issues:

- In the patch titled "ENH", the following lines break the compilation:
```
@@ -790,10 +815,13 @@ int OpenSSLStreamAdapter::BeginSSL() {
 #ifdef OPENSSL_IS_BORINGSSL
     DTLSv1_set_initial_timeout_duration(ssl_, dtls_handshake_timeout_ms_);
 #else
+#if (OPENSSL_VERSION_NUMBER >= 0x10100000L)
+    DTLSv1_set_initial_timeout_duration(ssl_, dtls_handshake_timeout_ms_);
```
DTLSv1_set_initial_timeout_duration doesn't exist in OpenSSL, and I could not find any comparable function in OpenSSL which serves the same purpose specifically for DTLS. I have commented it out for OpenSSL for the time being, to see that I make it to the end of the build. Is that a mistake in the patch?

- Unit tests - indeed failed in compilation, i have added rtc_include_tests=false, which resolves the issue

Which leaves us with the one thing that is stopping me from finishing the linking of obs-outputs:
```
"non-virtual thunk to cricket::WebRtcVideoCapturer::OnFrame(webrtc::VideoFrame const&)", referenced from:
      vtable for VideoCapturer in WebRTCStream.cpp.o
```
I verified that the symbols for it are in libwebrtc.a. Is this yet another flavor of the RTTI stuff? Any idea how to resolve that?

Also, I am happy to update everyone that I am no longer shouting at the computer profusely, everyt time the build fails. Call it Nirvana.

Thanks,
Eran

**Comment by klommenz** [comment]
Indeed, after building WebRTC in release config, and OBS in Debug mode everything went through, and I have a working build. Next is starting the integration with the server, and seeing that there are no dreaded runtime issues.

Also, for the record, I would like to mention that I ran into one hiccup when switching to WebRTC 69. I got this message:

```Undefined symbols for architecture x86_64:
  "webrtc::CreateBuiltinAudioDecoderFactory()", referenced from:
      WebRTCStream::WebRTCStream(obs_output*) in WebRTCStream.cpp.o
ld: symbol(s) not found for architecture x86_64
```

After checking build.GN and adding a line to specifically target that class, everything was fine. The issue was also reported on WebRTC forums:

https://bugs.chromium.org/p/webrtc/issues/detail?id=9528

Thank you everyone for your help. Hopefully I am going to have streams coming from OBS into my WebRTC server soon

Eran

**Comment by agouaillard-cosmo** [comment]
- Good to hear you succeeded the ordeal.
- out of curiosity, even with the guidance, how long did it take you, and what's your profile (how many years of experience with C++)?
- You are speaking about integrating with a server. Does it mean you do not plan to use it with the currently supported server (Janus video room, medooze, millicast, ....) but a different one? If this is the case, we always wanted to document the process to add a new signalling protocol (as long as the signalling transport protocol remains Webscoket or Rest), and we would be happy to guide you through in exchange for creating a first draft of the missing doc. Rest assured that it is in NO WAY as hard as going through the Google build process.

**Comment by agouaillard-cosmo** [comment]
Closed as successfully as per offline discussion
