### ISSUE TITLE
Static compile on windows 10, webrtc is very small

### ISSUE THREAD

**Issue by v5anyexiuluo** [CoSMoSoftware/OBS-studio-webrtc#68]
Help!
I compile the webrtc_69 on windows 10 after adding openssl.1.1.0g-patches. But i can not get the fully static webrtc library. The webrtc.lib is only 7M in size rather than more than 200M. The compile command as follow:
`gn gen out/release_openssl_share_69 --args="use_rtti=true rtc_include_tests=fa                                                                                                                 lse is_debug=false rtc_build_ssl=false rtc_ssl_root=\"../../../1.1.0j\""`
Is any mistake in the command? Any idea how to resolve that?

**Comment by agouaillard-cosmo** [comment]
As Written in the README:

If you think the compilation of the code from webrtc.org is too difficult, and it makes depending projects NOT easily reproducible, please let Google know, Their bug tracker is there: https://bugs.chromium.org/p/webrtc/issues/list

As answered in your previous ticket:

We strongly suggest that you wait until the end of the month to get the "community package" for liwebrtc. If you prefer not to wait, you are on your own.
