### ISSUE TITLE
Investigate Finding OpenSSL 1.1 properly on MacOS

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#70]
the FindOpenSSL.cmake module provided by CMake is not finding the right OpenSSL library even when providing an OPENSSL_ROOT_DIR form the command line. The right includes (from a brew install) are found, but the script still finds the system level libs !?

**Comment by agouaillard-cosmo** [comment]
WIP 4feb3ba

**Comment by agouaillard-cosmo** [comment]
just pass the full path and not the link through the OPENSSL_ROOT_DIR variable.
i.e. pass this:

        -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl\@1.1

**Comment by SCG82** [comment]
Have you tried this module? https://github.com/SCG82/OBS-studio-webrtc/blob/dev/cmake/Modules/FindOpenSSL.cmake
