### ISSUE TITLE
Have a GUI option to (en/dis)able libwebrtc logs

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#72]
libwebrtc logs can be quite verbose and are not always needed. We should be able to enable / disable them at runtime.

**Comment by SCG82** [comment]
Note: PR #147 has all console output in websocket-client converted from std::cout to native OBS logging (info, warn, error, debug)

**Comment by agouaillard-cosmo** [comment]
that will be helpful. However this ticket is about setting dynamically the level of internal libwebrtc logging. right now it s hardcoded, and does not have a corresponding GUI element.
