### ISSUE TITLE
m69 Windows : LoadLibrary failed obs-outputs.dll websocketclient.dll

### ISSUE THREAD

**Issue by david-bui** [CoSMoSoftware/OBS-studio-webrtc#74]
Branch m69
After compiling with this command : 
```
cmake -G"NMake Makefiles" -DQt5_DIR=C:\Qt2\5.12.3\msvc2017_64\lib\cmake\Qt5 -DDepsPath="C:\Users\David Bui\Downloads\dependencies2017\win64\include" -DCMAKE_BUILD_TYPE=Release ..
```
Running obs64.exe -> "Start Streaming"
an error occur with this following in the logs : 
```
15:27:14.247: ---------------------------------
15:27:14.248: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
15:27:14.530: [AMF] AMF Test failed due to one or more errors.
15:27:14.530: Failed to initialize module 'enc-amf.dll'
15:27:14.537: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
15:27:14.537:  (126)
15:27:14.539: LoadLibrary failed for '../../obs-plugins/64bit/obs-outputs.dll': The specified module could not be found.
15:27:14.539:  (126)
15:27:14.539: Module '../../obs-plugins/64bit/obs-outputs.dll' not loaded
15:27:14.549: LoadLibrary failed for '../../obs-plugins/64bit/websocketclient.dll': The specified module could not be found.
15:27:14.549:  (126)
15:27:14.549: Module '../../obs-plugins/64bit/websocketclient.dll' not loaded
```
[2019-05-17 15-27-13.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/3190340/2019-05-17.15-27-13.txt) 

Webrtc used : 69

What is expected ?
Streaming starts

**Comment by david-bui** [comment]
https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/868276ffac4d8943a537f8ea91a800b960b1c05a/plugins/websocket-client/CMakeLists.txt#L19-L20

This piece of code finds the first openssl installed on the system.
If OpenSSL is built with the default options on windows, it is the shared libraries that are built which caused the error.
When linking with static OpenSSL and crypt32, OBS doesn't complain anymore.

A fix will be suggested asap

**Comment by agouaillard-cosmo** [comment]
https://github.com/CoSMoSoftware/OBS-studio-webrtc/wiki/Dev-process

**Comment by agouaillard-cosmo** [comment]
If OpenSSL is built with the default options on windows, it is the shared libraries that are built which caused the error. On mac, it is linked with the static libraries.
When linking with static OpenSSL and crypt32, OBS doesn't complain anymore.

OK, this is very ambiguous. 
* First: english: one should say "linking against" and not "link to" or "link with"
* In our case, both libwebrtc and OBS can be linked against OpenSSL. It is not clear from the context which one you mean.

In the new design:
* libwebrtc is supposed to be using BoringSSL and link statically against it.
* websocket-client requires OpenSSL 1.1. I don't know if statically linking or dynamically makes a difference. 
* OBS uses MBDtls or something equivalent for RTMPS.
* We can point to the right OpenSSl build using the OPENSSL_ROOT. Here is for example my CmakeCache entry:
OPENSSL_ROOT_DIR:UNINITIALIZED=/usr/local/opt/openssl@1.1

for your patch, you can check the extension of the file pointed to by the following variables:
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/local/opt/openssl@1.1/lib/libcrypto.dylib
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/local/opt/openssl@1.1/lib/libssl.dylib

**Comment by david-bui** [comment]
Using the variable OPENSSL_ROOT_DIR seems the most cross-platform way to go - the documentation in the [wiki was updated](https://github.com/CoSMoSoftware/OBS-studio-webrtc/wiki/Dev-process)
