### ISSUE TITLE
Troubles with running OBS on Windows 10

### ISSUE THREAD

**Issue by kindritskyiMax** [CoSMoSoftware/OBS-studio-webrtc#81]
Hi. I have installed OBS and tried to run it from the shortcut. The problem is that link is pointing to C:\Program Files\OBS Studio (64bit)\bin\obs.exe but in my system, OBS was installed at C:\Program Files\OBS Studio (64bit)\bin\64bit\obs.exe with extra 64bit dir.

Also when I run downloaded installer my OS is complaining that exe installer is from an unknown publisher. I think it's related to code signing.

**Comment by agouaillard-cosmo** [comment]
Hi max, 

thank you for the feedback.

I opened two bugs for each separate issue (#82, #83), where you can follow our progress. We think we will be able to fix it in the next weeks or so.
