### ISSUE TITLE
Compile 21/73 under linux

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#84]

**Comment by ValentinRamirezCosmo** [comment]
OBS and the mobule obs-outputs are now loaded correctly in Linux.
Unfortunately, it is not functionnal. The call to **webrtc::CreatePeerConnectionFactory** leads to the following : 
```
Thread 17 "worker" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff92a00700 (LWP 18086)]
0x00007fff9b9a851c in rtc::webrtc_checks_impl::FatalLog (file=0xa30203a726f7272 <error: Cannot access memory at address 0xa30203a726f7272>, line=1696623973, 
    message=0x207473616c20230a <error: Cannot access memory at address 0x207473616c20230a>, fmt=0x353520656e696c20) at ../../rtc_base/checks.cc:127
127     ../../rtc_base/checks.cc: No such file or directory.
```

**Comment by agouaillard-cosmo** [comment]
This is blocked on #79 

Ludo, we need a community package. For OBS it means something different:
we need a zip of the install directory, so we can install from command line without GUI.
Can you prepare that? The validation process involve streaming to millicast and checking that the logo appear in the video received in loopback from the web client. If you re not clear about the validation process, let me know and i ll document it better in a wiki page.

**Comment by agouaillard-cosmo** [comment]
done.
