### ISSUE TITLE
Receive WebRTC as MediaSource in OBS

### ISSUE THREAD

**Issue by jahe7959** [CoSMoSoftware/OBS-studio-webrtc#91]
Is this possible and if yes, how? Thanks!!

**Comment by agouaillard-cosmo** [comment]
OBS is send-only, I'm not sure what you are asking for.

**Comment by jahe7959** [comment]
Oh sorry. 
I want to receive WebRTC like i can recieve RTMP or NDI as a video-Input source.

**Comment by agouaillard** [comment]
This implementation can not do that.
