### ISSUE TITLE
EBS: No clear way to pick VP8 or VP9, encoder looks like h264?

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#93]
This is in the Windows build

It's unclear what is being used to stream to the room -- is it vp8, vp9, or h264?  I assume it's not h264, and my gut tells me vp9 if not an option is likely not the default.  

How to pick between vp8 and vp9?

**Comment by chadfurman** [comment]
FYI I cannot put this ticket in a project.  I know you asked I put it in the Evercast project, but I do not have that power.  The "projects" field is static and I cannot change it.

**Comment by skastr0** [comment]
From what I can see there's no videocodec param Evercast's Janus configure request so it ends up using the room's default which is vp8. I was able to compile a version using vp9 by adding that param to the request.

**Comment by agouaillard-cosmo** [comment]
@skastro is correct.
I will add today a codec multiple choice menu in the settings UI, just like MilliCast does it.

**Comment by agouaillard-cosmo** [comment]
done.
