### ISSUE TITLE
EBS: Recording button still visible

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#94]
The "start recording" button and other recording-related UI elements are visible.

**Comment by agouaillard-cosmo** [comment]
This is part of the 10 "Extra Questions" ask by Brad on June 19th. It is documented in the shared document "Evercast: Extra Questions."  My understanding is that it was not part of this work at this time. Please Advise.

**Comment by chadfurman** [comment]
Removal of recording button and options is part of the branding / skinning effort that I was under the impression you were taking on.  It is a requirement for us to go live with the EBS build, and if you're not including it then we'll have to hack it out like we did before.  What are your thoughts?

**Comment by agouaillard-cosmo** [comment]
Let me check how much effort is involved.

**Comment by chadfurman** [comment]
Let us know.  You can also describe the effort necessary and we can assist.  I know you were aiming to include it in the consulting hours, so maybe it's a better use of your time to spend 30min or so describing the task steps and then delegate the work to Castro?

**Comment by agouaillard-cosmo** [comment]
Started.

**Comment by agouaillard-cosmo** [comment]
For security reasons, recording API should also be removed to avoid people starting and stopping recording through the API even if there is no corresponding GUI.
