### ISSUE TITLE
EBS: Dropdowns show non-Evercast options

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#95]
It does default to Evercast, though the dropdown shows non-Evercast options.  It's good that it defaults to Evercast -- is it possible to remove the other options?

**Comment by agouaillard-cosmo** [comment]
This is also part of the Extra Request by Brad, documented in the shared document. My plan was to finish the contractual work first (namely VP9, 1080p, and installers) first. Please advise.

**Comment by chadfurman** [comment]
VP9 yes, 1080 we will have to reproduce in a new build with compiler optimizations first and then get you the adapter if need be.  This also is part of the branding effort that we thought was included in the skin work you were doing -- if not, we'll have to hack this in again.  What are your thoughts?

**Comment by agouaillard-cosmo** [comment]
I can take care of the drop down now.

**Comment by chadfurman** [comment]
Thanks :)

**Comment by agouaillard-cosmo** [comment]
fixed.
