### ISSUE TITLE
EBS: Question about Bitrate

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#96]
Are the audio and video bitrate controls expected to work?  If not, what is the default bitrate for each?

**Comment by agouaillard-cosmo** [comment]
It should work exactly like your version of EBS. If it does not, please report.

**Comment by chadfurman** [comment]
Closing this for now.  Will report back when VP9 is connecting as expected and more testing is conducted.  So far, I believe this is working.  If not, I'll make a new ticket.
