### ISSUE TITLE
EBS: ebs-studio folder in Application Support not being used

### ISSUE THREAD

**Issue by skastr0** [CoSMoSoftware/OBS-studio-webrtc#97]
Seems like the vendor_skin build is still using the obs-studio folder which causes profiles, scenes etc to be shared between both apps.

**Comment by agouaillard-cosmo** [comment]
Are we expecting to have OBS installations next to EBS installation on the same computer?

**Comment by chadfurman** [comment]
At the moment, this isn't a situation we run across.  However, I am predicting that as we expand into the gaming industry that this will likely be a situation we come across.  I'm not sure we'll have conflicts -- just shared settings.  If it ends up being in conflict / if EBS corrupts the settings of the OBS client, then it will become a higher priority issue and may need quick remediation.  So I'm just trying to look forward and eliminate problems before they arise.

What are your thoughts?

**Comment by SCG82** [comment]
PR #147 has all settings in a separate configurable folder (defaults to obs-webrtc) for both macOS and Windows (Linux untested)

**Comment by agouaillard-cosmo** [comment]
done.
